### ISSUE TITLE
Add bad_trigger_phases to conditions database for flagging.  

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#103]
Creating a bad_phases condition in the database, to determine which trigger phases are "good" and which ones were "bad" for a given run.  Modifying the SvtEventFlagger to use the values in the bad_trigger_phases conditions to determine which events to flag as having bad latency.  Which runs will contain bad phases will be determined by the shaping time (which is related to latency)

**Comment by JeremyMcCormick** [comment]
This is not necessarily how we want to do this.  The shaping time is also unrelated.  Closing for now.
