### ISSUE TITLE
Update location of hps-java reference tests

### ISSUE THREAD

**Issue by pbutti** [JeffersonLab/hps-java#1031]
We should move the location of the reference tests to a public page on s3df. 
A possibility is to register for a public domain and move the files there to be accessible for everyone. 
Paths in the tests should be changed accordingly. 

Here some infos from Omar:

https://s3df.slac.stanford.edu/public/doc/#/service-compute?id=s3df-static-sites
[6:09](https://ldmx.slack.com/archives/D018V5DET2Q/p1714493362490129)
just put the files under /sdf/data/hps/public_html
[6:09](https://ldmx.slack.com/archives/D018V5DET2Q/p1714493382083489)
and it will be accessible from https://s3df.slac.stanford.edu/data/hps

Current files can be dowloaded from:
https://hpsweb.jlab.org/test/hps-java/

@mholtrop

**Comment by mholtrop** [comment]
@pbutti and @bloodyyugo 
Thank you for that information. These files being at JLab makes them ***more*** public than putting them on s3df at SLAC, since all (nearly all) members of HPS have a JLab account but not all have SLAC accounts.

The files can be found at JLAB on disk at: /u/group/hps/www/hpsweb/html/test/hps-java/referencePlots/

**Comment by pbutti** [comment]
@mholtrop 
Very good! I didn't know the location on jLab, I'm very happy you found it. I'll note it down on confluence under the tests area. I might have misread your last message on PR #1030 
Since I do not have a jLab account if I provide the reference file, would you or @bloodyyugo be able to update it so  we can test again the PR ?

**Comment by mholtrop** [comment]
Yes, I can put the file there.

**Comment by pbutti** [comment]
@mholtrop 
Could you please upload these two? This zip file contains PhysRun2016V0ReconTest plots, which should be placed here `referencePlots/PhysRun2016V0ReconTest` I think
[V0.zip](https://github.com/JeffersonLab/hps-java/files/15191493/V0.zip)
