### ISSUE TITLE
Identify and fix memory leak in recon

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#107]
There appears to be a memory leak in our reconstruction. Shown here is a plot of the total memory versus event number.

![recomemoryvseventnumber](https://cloud.githubusercontent.com/assets/14838926/26795370/42312bfe-49da-11e7-9f64-3d663a8e165b.png)

**Comment by normangraf** [comment]
To replicate this plot, you can fetch recon/src/main/java/org/hps/recon/utils/ReconDiagnosticsDriver.java from the iss87 branch, add it to the end of your Driver list in your steering file and set debug to true. It will print out a string of diagnostic quantities that you can then plot to follow the memory usage.
JProfiler or some other similar profiling tool should be able to identify the source of the leak.

**Comment by JeremyMcCormick** [comment]
How are you running the recon?  Is this loading an existing LCIO file or you're using evio2lcio?

**Comment by normangraf** [comment]
?This is from scratch, viz. evio2lcio.


________________________________

**Comment by JeremyMcCormick** [comment]
To reproduce:

```
java -server -DdisableSvtAlignmentConstants -cp hps-distribution-3.11-SNAPSHOT-bin.jar org.hps.evio.EvioToLcio -x PhysicsRun2016FullRecon.lcsim -d HPS-PhysicsRun2016-v5-3-fieldmap_globalAlign -DoutputFile=tst /nfs/slac/g/lcd/ilc_data3/hps/data/physrun2016/evio/hps_008054.evio.0 
```

**Comment by JeremyMcCormick** [comment]
@normangraf 

Which JVM version are you using?

I can't replicate what you are seeing without knowing this.

**Comment by JeremyMcCormick** [comment]
I don't see anything that looks like a memory leak when I run the reconstruction using Java 1.8.

![image](https://user-images.githubusercontent.com/2194163/26857496-c22919ba-4adf-11e7-9152-67e97686f8b8.png)

![image](https://user-images.githubusercontent.com/2194163/26857515-e413f0cc-4adf-11e7-8cdf-8d131741154c.png)

![image](https://user-images.githubusercontent.com/2194163/26857535-0a5e9e8a-4ae0-11e7-90fa-9f50126c687d.png)

![image](https://user-images.githubusercontent.com/2194163/26857580-4c92eed2-4ae0-11e7-9e05-4fd9b402e1d1.png)

**Comment by JeremyMcCormick** [comment]
By the way, I don't think we want to run with the `-server` option because as far as I understand it that will cause the JVM to permanently claim memory and never give it back to the operating system, which is bad if there is a memory spike.  I'm running locally without this option and it seems fine -- in fact it appears that it might be running faster with this option as the GC seems less frequent.

**Comment by normangraf** [comment]
Thanks Jeremy. I was using the default JVM on SLAC Linux: 1.7. I thought the -server option primarily invoked the JIT compiler earlier and more aggressively. I'll rerun some tests and let you know what I find.

**Comment by JeremyMcCormick** [comment]
Can you rerun with Java 1.8 and no -server flag?

**Comment by normangraf** [comment]
Do you know how I setup Java 1.8 on SLAC rhel6-64?

**Comment by omar-moreno** [comment]
https://www.slac.stanford.edu/comp/java/

Set JAVAVER to the version you want to use.

**Comment by normangraf** [comment]
Thanks.

**Comment by JeremyMcCormick** [comment]
Also I'd recommend running with -Xmx1g and -Xmn1g to pre-allocate the JVM
heap size at 1 gig for the job.  Otherwise it will be varying the heap size
as it runs and the available memory value could vary.

**Comment by normangraf** [comment]
I've rerun using jdk1.8 and also run without the -server option. I see similar behavior. I also do not see any appreciable difference in execution time. Here is a plot of total memory, as reported by runtime.totalMemory() in MB as a function of event number. This job actually crashed when it exceeded the maximum memory (910 MB).

![memoryusage_20170608](https://user-images.githubusercontent.com/14838926/26939820-66842a7e-4c2d-11e7-8280-332f779c6c42.png)

However, I don't see us getting anywhere near 2GB, so I think we should study this a little more before requiring more than 2GB for our production jobs at JLab.

Here's the command-line:

java -DdisableSvtAlignmentConstants -cp hps-distribution-3.11-SNAPSHOT-bin.jar org.hps.evio.EvioToLcio -x PhysicsRun2016FullRecon.lcsim -d HPS-PhysicsRun2016-v5-3-fieldmap_globalAlign -DoutputFile=8054.0.jdk1.8 /nfs/slac/g/lcd/ilc_data3/hps/data/physrun2016/evio/hps_008054.evio.0

I have added org.hps.recon.utils.ReconDiagnosticsDriver at the end of the Driver list in the steering file to print out statistics at the end of every event. That Driver is currently on branch iss87.

**Comment by mholtrop** [comment]
Not clear this is a real issue or a Java behavior.
