### ISSUE TITLE
Fix speed bottlenecks in track recon

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#117]
Modifications to the track recon code that should speed it up without changing the output at all.

**Comment by mdiamon** [comment]
I have now discovered, there are a couple similar bottlenecks in the GBL as well, which can be solved without changing the output.

**Comment by normangraf** [comment]
?What unit or integration tests are you using to confirm the performance?


________________________________

**Comment by mdiamon** [comment]
?I'll give an update at next week's tracking and/or software meeting; let's discuss then.


-- Miriam


________________________________

**Comment by JeremyMcCormick** [comment]
Resolved by #162.
