### ISSUE TITLE
Speed up pulse-fitting algorithm by caching combinations of parameters

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#118]
Formula is 

 if (time < 0) {
                return 0;
            }
            //===> return (time / channelConstants.getTp()) * Math.exp(1 - time / channelConstants.getTp());
            return (Math.pow(tp, 2) / Math.pow(tp - tp2, 3))
                    * (Math.exp(-time / tp)
                    - Math.exp(-time / tp2) * (1 + time * (tp - tp2) / (tp * tp2) + 0.5 * Math.pow(time * (tp - tp2) / (tp * tp2), 2)));
//            return (time / tp) * Math.exp(1 - time / tp);

Could be made faster if certain combinations of tp and tp2 were cached.

**Comment by sebouh137** [comment]
there are two branches for this.  iss118 and iss118a.  These each represent different solutions for improving the speed on this.  (118a being an extension of 118, with further modifications to make it run faster).

**Comment by JeremyMcCormick** [comment]
Resolved by PR #145.
