### ISSUE TITLE
Add EventFlagFilter to PhysicsRun2016FullRecon.lcsim

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#122]
filter on bias, position, and burst-mode noise and event-header

**Comment by normangraf** [comment]
`` <driver name="EventFlagFilter" type="org.hps.recon.filtering.EventFlagFilter">
<flagNames>"svt_bias_good" "svt_position_good" "svt_burstmode_noise_good" "svt_event_header_good"</flagNames>
</driver>
``

**Comment by sebouh137** [comment]
should I also make similar changes to all of the other similar drivers for 2016 as well?

**Comment by sebouh137** [comment]
also @normangraf , are the quotes around the names of the flags needed?

**Comment by sebouh137** [comment]
In this branch, I have propogated the changes that Norman and I have independently made on the main 2016 recon steering file to the other 2016 recon steering files (eg, PhysicsRun2016FullReconPair0, etc.)

**Comment by JeremyMcCormick** [comment]
PR #123 resolves this?

**Comment by sebouh137** [comment]
if you accept pull request 123, yes, it will resolve this.

**Comment by JeremyMcCormick** [comment]
This will be resolved by PR #123.
