### ISSUE TITLE
internally speed up the helix intersection code through low-level stuff

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#125]
First, i will reduce the number of calls to hep.physics.vec.VecOp.inverse inside of org.hps.recon.tracking.MultipleScattering.getHelixIntersection

**Comment by omar-moreno** [comment]
Hi @sebouh137, if you are planning on making changes to the tracking code, you should first bring it up to the tracking group so we can come up with a plan as to how to validate your changes. Also, it would be good to see why you feel that this needs to be changed.

**Comment by mdiamon** [comment]
I'm already covering this in issue117
