### ISSUE TITLE
Unit tests for track reco

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#134]
Update and improve the unit tests in hps-tracking/src/test/java

**Comment by JeremyMcCormick** [comment]
This will be resolved by PR #144.

**Comment by mdiamon** [comment]
Re-opening because I have just upgraded the tests, in branch iss134b.  There are now proper track residuals (I hadn't been able to get these working before).
Updated versions of reference plots (http://www.lcsim.org/test/hps-java/referencePlots/ap_prompt-ref.aida , http://www.lcsim.org/test/hps-java/referencePlots/hps_005772-ref.aida) go with these.
