### ISSUE TITLE
Create an interface SiliconResolutionModel for use in strip making

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#135]
(calculates resolution in measured direction)

**Comment by JeremyMcCormick** [comment]
@sebouh137 

Can you explain a bit further about why you want to do this?

**Comment by sebouh137** [comment]
In the StripMaker, there are parameters for determining the error in the position measurement for a cluster.  This error is the strip pitch (the width of each individual strip) multiplied by one of several constants, depending on how many hits are in the cluster.   Currently, the constants are 1/sqrt(12) if there is one hit, 1/5 if there are 2 hits, 1/3 if there are 3 hits, 1/2 if there are 4 hits, and 1 if there are 5 or more hits.  I asked on the tracking slack channel where these came from, and Tim said "Ahh… this one slipped by me.  Pretty sure I answered this when Norman asked previously.  These are loose rules of thumb developed from test beam with CDF sensors using similar geometry to those used in HPS.  However, they are NOT accurate estimates for all sensor geometries. In the absence of test beam for our sensors, one can use the aligned detector as a telescope to determine these, and/or (one step simpler and less accurate) use MC to determine them (trusting the charge deposition and digitization simulation).  Both procedures have caveats, but the constraints are there to get the right answer if we’re willing to do all the work!  I would advocate at least using the MC to derive these, as that’s probably closer than what’s there now.  (P.S.  These should be replaced by calls to an interface, SiliconResolutionModel, or some such…)"

**Comment by mdiamon** [comment]
a stub you might want to build on: StripResolutionModel.java (implements ResolutionModel) in org.lcsim.recon.tracking.digitization.sisim

**Comment by mdiamon** [comment]
Resolved by #217
