### ISSUE TITLE
Update track-cluster matching for 2016 data

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#146]
improvements in track-cluster matching for 2016 data, with a new set of parameters more appropriate for 2.3 GeV data.

Features:
1) "snap-to-edge":   ignores the difference in position in y if the cluster contains only hits on edge crystals and the track is closer to the edge than the cluster.  
2)  L6/no L6:  use different set of parameters when there is no hit in layer 6.  
3)  removed non-GBL tracks.  (because nobody cares about matching matched tracks to clusters).

**Comment by sebouh137** [comment]
branch was previously named dev-tc-match.  This branch predates our usage of github and the issXX branch-naming scheme.

**Comment by JeremyMcCormick** [comment]
@sebouh137 

Is this covered by PR #147?

**Comment by sebouh137** [comment]
yes, this is covered by pull request 147.

**Comment by JeremyMcCormick** [comment]
This is resolved with PR #147.
