### ISSUE TITLE
Fix non-determinism in track reconstruction

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#152]
<img width="411" alt="tracks10" src="https://user-images.githubusercontent.com/28606323/28037908-e4d4662a-6571-11e7-8f0f-63b09ff272fc.PNG">
<img width="410" alt="tracks14" src="https://user-images.githubusercontent.com/28606323/28037909-e4d596bc-6571-11e7-95a7-d874b0fd54e3.PNG">
miriam_diamond [11:26 AM] 
I performed raw->reco LCIO on the first event of a skim file.  I did this 4 times.  Each of the first three times, I got 10 MatchedTracks.  The fourth time, I got 14 MatchedTracks.  The difference is in the number of tracks found by the last 2 strategies.  So, there's some non-determinism that should be eliminated.

First fix attempt: for any HashMap whose entries are iterated over, change it to LinkedHashMap

**Comment by JeremyMcCormick** [comment]
Resolved by PR #153.

**Comment by mdiamon** [comment]
In **HelicalTrackHitDriver.process()**, changing **Map<HelicalTrackStrip, SiTrackerHitStrip1D> stripmap** from HashMap to LinkedHashMap is enough to make the results deterministic, but is just a patch.  The fundamental problem is that the track formation depends upon the order of the hits in the HelicalTrackHit collection.  In future, this should be solved by sorting HelicalTrackHits by some quality metric before inputting to SeedTracker.
