### ISSUE TITLE
Mistake in "HPS-PhysicsRun2016-v5-3-fieldmap_globalAlign" detector name in compact.xml 

### ISSUE THREAD

**Issue by brigidcrowe** [JeffersonLab/hps-java#155]
The detector name in the "HPS-PhysicsRun2016-v5-3-fieldmap_globalAlign" compact.xml was set as "HPS-PhysicsRun2016-**Nominal**-v5-3-fieldmap_globalAlign", and creates a "ConditionsNotFound" exception. 

The correct name is set in 'detector.properties', so it only needs to be changed in the compact.xml (and then rebuild the .lcdd).

**Comment by afilippi67** [comment]
For consistency with general geometry naming, I guess it would be better keep the name inside the compact, and add the missing "Nominal" everywhere else (geo directory name, properties file, lcdd), as I suppose it was simply forgotten upon making the new folder.
If the name becomes too long, "globalAlign" can be dropped.
     Alessandra

**Comment by JeremyMcCormick** [comment]
Should be resolved by #156.
