### ISSUE TITLE
Implement pulse fitting for cosmic calibration

### ISSUE THREAD

**Issue by LucaMarsicano** [JeffersonLab/hps-java#159]
Implement Pulse Fitting for Cosmic Calibration

**Comment by JeremyMcCormick** [comment]
This Driver in hps-users could perhaps be used as a starting point:

https://github.com/JeffersonLab/hps-users/blob/master/src/main/java/org/hps/users/jeremym/EcalCosmicHitFitDriver.java

**Comment by JeremyMcCormick** [comment]
This is old and can probably be closed (does it still need to be done?).

**Comment by JeremyMcCormick** [comment]
I'm closing this as it is old.  There's already multiple implementations of pulse fitting for ECal data.
