### ISSUE TITLE
Change target position to z=0 in tuple makers

### ISSUE THREAD

**Issue by brigidcrowe** [JeffersonLab/hps-java#167]
The -5mm target position for 2015 is dubious, and 2016 data suggests the position is closer to z=0. Best to set it to that value until the true position is sorted out.

**Comment by mdiamon** [comment]
In the new versions of the tuple makers I #312 # there is no target position.  All the calculations involving target position have been moved upstream into the appropriate drivers; the tuple makers now only fetch values rather than re-calculating values.
