### ISSUE TITLE
Cache and use field map data files automatically

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#168]
It is annoying that symlinks need to be created manually to run hps-java on detectors with fieldmaps.  Instead these files should downloaded and used automatically.

**Comment by mholtrop** [comment]
Maybe annoying, however on a firewalled farm (or in an airplane), the "download automatically" won't work and break the code completely, which is a lot more annoying. 
Possible solution: Find the field map from an environment variable?

**Comment by JeremyMcCormick** [comment]
Why not just pre-cache the field map dat files into the cache dir so the download isn't needed when you run?

**Comment by mholtrop** [comment]
That seems fine, as long as there are clear instructions on how to populate the cache dir for offline machines.

**Comment by normangraf** [comment]
We set up access to the field map in this way in order to keep slic standalone. But you are right that it is a pain to have to remember to manually set things up in the java environment, whether it be running reconstruction, running tests during builds or running JAS3 for data inspection or event displays.

**Comment by JeremyMcCormick** [comment]
This issue also prevents tests using data from "fieldmap" detectors from running locally as the symlink is not setup by default.

**Comment by JeremyMcCormick** [comment]
> We set up access to the field map in this way in order to keep slic standalone.

Why don't we have separate filename and url attributes? 

Then the url to cache will not have any effect on the LCDD output, which can just stay the same as it is now.

**Comment by normangraf** [comment]
Here's some example code which checks to see whether a fieldmap exists (either as a file or as a symlink). If it does not, it creates a symlink to the cached file. If the fieldmap does not exist in the user's cache, it downloads it from the web. If run on Windows it requires the user to run as administrator. We should discuss how best to package this functionality to make it easy to use. We could wrap it as a utility class to start with. Let me know what you think.

```import java.io.File;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import junit.framework.TestCase;
import org.lcsim.util.cache.FileCache;

/**
 *
 * @author Norman A. Graf
 */
public class CachedFieldmapTest extends TestCase {

    static final String fieldMapURLBase = "http://www.lcsim.org/resources/hps/fieldmap";
    static final String fieldMapName = "125acm2_3kg_corrected_unfolded_scaled_0.7992.dat";

    public void testIt() throws Exception {
        //does the file exist?
        Path existingFile = Paths.get("fieldmap/" + fieldMapName);
        if (Files.exists(existingFile)) {
            System.out.println("File " + fieldMapName + " exists");
        } else {
            // does a symbolic link exist?
            if (Files.isSymbolicLink(Paths.get(System.getProperty("user.dir") + "/fieldmap/" + fieldMapName))) {
                System.out.println("Symbolic link exists");
            } else {
                System.out.println("Downloading fieldmap and creating symbolic link");
                FileCache cache = new FileCache();
                URL fieldMapUrl = new URL(fieldMapURLBase + "/" + fieldMapName);
                File field = cache.getCachedFile(fieldMapUrl);
                Path target = field.toPath();
                System.out.println("target = " + target);
                System.out.println("working directory = "+System.getProperty("user.dir"));
                Files.createDirectories(Paths.get(System.getProperty("user.dir") + "/fieldmap"));
                Files.createSymbolicLink(Paths.get(System.getProperty("user.dir") + "/fieldmap/" + fieldMapName), target);
            }
        }
    }
}```

**Comment by normangraf** [comment]
Hmmm, does code formatting not work?

**Comment by JeremyMcCormick** [comment]
> Hmmm, does code formatting not work?

You need triple backticks at the start and end of your code block.

**Comment by normangraf** [comment]
Thanks. The "Insert Code" tool doesn't do that.

**Comment by JeremyMcCormick** [comment]
> Here's some example code which checks to see whether a fieldmap exists

I think this is overly complicated.

Instead I'd propose we just list separately a remote url and a filename e.g.

```
<field type="FieldMap3D" name="HPSDipoleFieldMap3D"
  filename="fieldmap/125acm2_3kg_corrected_unfolded_scaled_0.7992.dat"
  url="https://raw.githubusercontent.com/JeffersonLab/hps-fieldmaps/master/125acm2_3kg_corrected_unfolded_scaled_0.7992.tar.gz" />
```

The LCDD converter will use the filename attribute, and lcsim will attempt to download, cache and untar the file at the remote URL.

This allows separating entirely the LCDD filename from the URL used by hps-java, and it also means we do not need to regenerate any LCDD files.

**Comment by normangraf** [comment]
We'll need to update the compact.xml descriptions and write some code to handle the url parsing, caching and unpacking, but in the long run I agree that it is preferable.

**Comment by JeremyMcCormick** [comment]
I've implemented the necessary functionality in the iss4 branch of lcsim and the iss168 branch of hps-java if you want to try it.

The only change to hps-java was updating the compact.xml files to contain an additional url pointing to the remote file.

**Comment by JeremyMcCormick** [comment]
Functionality has been implemented and merged into lcsim master from the iss4 branch.

I'm going to close this - further discussion should be moved to the PR #169 page.
