### ISSUE TITLE
Propagate MC links in readout simulation

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#181]
Propagate and persist cluster to MCParticle and other MC relations into output when performing pileup/readout/trigger simulation.

**Comment by mccaky** [comment]
As of the iss166 merger, truth relations are now propagated into readout. The truth relations are presently lost during raw conversion in reconstruction, however. Correction of this should probably be handled separately as part of a greater set of cleanup concerning the raw conversion drivers.
