### ISSUE TITLE
TrackResidualsRelations weird behaviour

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#194]
If MergeTrackCollections.setRemoveCollections is false, some of the TrackResidualsRelations seem broken. 
 The FetchResidualsTest does raw->reco lcio, using ReconTestSkeleton.java, and then executes the FetchResiduals driver to read the tracks and TrackResidualsRelations back in from the reco lcio.  Note the "null TrackResidualsData for track ******" appearing sporadically in the test output, meaning that a track in the MatchedTracks collection has no corresponding entry in TrackResidualsRelations.  In ReconTestSkeleton.MainTrackingDriver, change `mtc.setRemoveCollections(false)` to `mtc.setRemoveCollections(true)` and poof no more nulls.  Also note that if mtc is removed altogether, no nulls.

**Comment by JeremyMcCormick** [comment]
Sorry, this has been sitting here for awhile...

I am not clear on what is causing this, but the way LCIO works is that objects have "pointer" locations; from what I understand these values are initially based on their memory addresses.  These pointers can be used to reference these objects, e.g. from LCRelations, and they are persisted when the file is written.  Something is obviously going wrong with this when the extra collections are included.  Either the pointer values are getting corrupted or set to something invalid, or they are just 0.  It might be possible to debug this by putting some print outs into the LCIO persistency code to show what these values are set to when the file is being read back in.

One guess at how to solve this: It is possible that we might need to mark the collections as "subsets" (don't remember exactly how but there is a flag/setter to do this) as this will tell LCIO that these objects are duplicates of ones in other collections.  This makes sure that the original object's pointers are used when making the relations.

**Comment by mdiamon** [comment]
In any case, the calculation of the residuals in this Driver needs to be updated, to use the new trackstates-at-sensors and to use a better extrapolation.
