### ISSUE TITLE
Split users module into different git repo

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#2]
The users module should be split into a separate git repository that depends on hps-java.

Example here of doing this with a branch filter:

https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by omar-moreno** [comment]
This should be done very soon.

**Comment by omar-moreno** [comment]
This was resolved with PR 53021f061a51baae36d3b976b3563a0e056b05cc.
