### ISSUE TITLE
Implement Kalman-based track following algorithm

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-java#204]
Algorithm has already been implement but needs to be integrated into hps-java.

**Comment by robertprestonjohnson** [comment]
It's not fully implemented yet!  The basic track fitting is working.  There is now an algorithm to fit the first few points to generate a seed, and work is in progress to generalize the fitting to work with a non-uniform field.  Pattern recognition (i.e. hit selection, removal, etc.) is not yet implemented.

**Comment by omar-moreno** [comment]
Resolved by #644
