### ISSUE TITLE
Sectoring in track reconstruction?

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#208]
All the basic machinery appears to be present in hps-java to implement sectoring, but it's not actually being performed.  The goal of sectoring is to leave the final tracking results unaffected, while significantly improving the runtime.

**Comment by mdiamon** [comment]
More detailed explanation: The sector size is set so large that the entire detector is considered one sector in phi, and two sectors (top vs bottom) in z.  But for some reason, setting the number of phi sectors to a larger number (e.g. 4) finds more tracks.

**Comment by JeremyMcCormick** [comment]
@mdiamon What's the status of this?  Is there a task here to be done?

**Comment by mdiamon** [comment]
It's a mystery why setting the number of phi sectors to greater than 1 finds more (rather than fewer) tracks.  This behavior is completely counter-intuitive.  Ideally we would like to investigate why ... but realistically, we're just leaving sectoring turned off, and leaving it alone.

**Comment by JeremyMcCormick** [comment]
Track sectoring is turned off for now; reopen this issue if work will be done on this task.
