### ISSUE TITLE
Update EngRun2015 to do Ecal time offsets in separate driver

### ISSUE THREAD

**Issue by hszumila** [JeffersonLab/hps-java#223]
This has been implemented for the 2016 data. First, we must combine EcalRawConverter2 and EcalRawConverter. Then the time correction driver must be added to all steering files to happen after EcalRawConverter. All steering files should use this. This has no effect on MC for now because the time corrections are done in EcalRawConverter.

**Comment by JeremyMcCormick** [comment]
I guess this was resolved.  Again, please close out issues when the corresponding branch has been merged.
