### ISSUE TITLE
Move recon 'fixes' and 'tweaks' out of tuple driver

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#227]
https://github.com/JeffersonLab/hps-java/blob/master/analysis/src/main/java/org/hps/analysis/tuple/TupleDriver.java

All 'tweaks' and 'fixes' to recon data need to be moved out of this class into upstream drivers so that they are reflected in the corresponding LCIO and DST files.  These fixes should not just exist in the tuple output.

Especially, there seems to be a whole interface for making corrections to the tracks and track states, which does not belong here at all.  These corrections should be applied in the standard recon chain rather than only be applied to data that is written to the tuples.

Amongst other places, there is code starting at this line which seems to alter/tweak tracks and track states:

https://github.com/JeffersonLab/hps-java/blob/c1f1fdb9197ee7ffd5ad9be2cc3b8ede2d6924a8/analysis/src/main/java/org/hps/analysis/tuple/TupleDriver.java#L720

This and related code should be refactored into separate methods and I would think these changes belong in the actual recon chain and not just as tweaks to tuple output.  If there are personal fixes/alterations which need to exist outside our recon chain, then I would think these belong in user's ROOT scripts and not in a class which is just supposed to be writing tuple output representing the recon data.

**Comment by mdiamon** [comment]
Corrections to tracks/trackstates can already be applied upstream using the TrackTweakDriver, which is the proper place.  The code for these corrections in the tuple driver is duplicating functionality in TrackTweakDriver and can simply be removed.
Residuals should be taken from the TrackResiduals collections created by TrackDataDriver; this code needs to be updated to access the new trackstates-at-sensors and calculate intercepts more accurately.

**Comment by mdiamon** [comment]
Changes to TupleDriver (someone should check that all desired values still get put into the trees properly):
- track extrapolation done using the new trackstates-at-sensors, properly taking into account the tilt of the sensors, with the help of some new TrackStateUtils methods.
- old addVertexVariables method still exists.  new method addVertexVariables(boolean doBsc, boolean doTar, boolean doVzc) allows beamspot-constrained, target-constrained, and/or z-constrained vertices to be disabled.  Same with fillVertexVariables method.
- old addParticleVariables method still exists.  new method addParticleVariables(String prefix, boolean doTrkExtrap, boolean doRaw, boolean doIso) allows track extrapolations, raw hit info, and/or isolation info to be disabled.  same with fillParticleVariables method.
- variables and corresponding set methods for "tweaks" removed.  references to them in steering files also removed.
- removed duplicate variable TrkHits (stored same information as NTrackHits)
- code cleanup to make it easier to read and maintain

**Comment by mdiamon** [comment]
Waiting on #250 for proper testing

**Comment by JeremyMcCormick** [comment]
Resolved by #265.
