### ISSUE TITLE
Improve event pileup simulation

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#232]
Try to improve how pileup is dealt with.

A lot of tracks are missing a hit in the first layer in the 2016 dataset, and this fraction appears to increase with beam current.

**Comment by JeremyMcCormick** [comment]
This is a pretty vague task.  What are you proposing be done?

**Comment by JeremyMcCormick** [comment]
I'm closing this because it is too vague.  I think it also duplicates #228.
