### ISSUE TITLE
Review and approve recon steering for EngRun2015 pass7

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#233]
- [x]  Set `_patchVertexTrackParameters` to false in `HpsReconParticleDriver`
- [x]  Expose the beam spot and target position and beam spot resolution in the steering file (different for 2015 and 2016)
- [x]  Limit creation of ReconstructedParticles to GBL tracks (remove MatchedTracks from list of Track Collections to process)

**Comment by normangraf** [comment]
I've updated the 2015 steering file and added a loose V0 filter.

**Comment by JeremyMcCormick** [comment]
Appears to have been merged...please close out github issues when you resolve them!
