### ISSUE TITLE
Track extrapolation: to tilted plane, with fieldmap

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#241]
We currently have methods to 
- extrapolate a track, with fieldmap, to a fixed z position
- find intercept of a helix with an arbitrary plane, without fieldmap
Since sensors are tilted with respect to the global axes, and the field changes significantly around some sensors (i.e. Layer 6), we need a method that combines the above functionalities: i.e. finds the intercept of a helix with an arbitrary plane with fieldmap.

**Comment by JeremyMcCormick** [comment]
Resolved by #281.
