### ISSUE TITLE
Update GBLOutput

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#248]
https://github.com/JeffersonLab/hps-java/blob/master/tracking/src/main/java/org/hps/recon/tracking/gbl/GBLOutput.java has a lot of code cut-and-pasted from other drivers, which does not get updated when the other drivers do.  Avoid this problem by replacing as much of the code in GBLOutput as possible with calls to the appropriate methods in other drivers / utils.

**Comment by mdiamon** [comment]
- Truth MC information is apparently not working.  needs to be fixed.
- Beamspot information is now obtained elsewhere.  should be eliminated here.
- Dummy covariance matrix being written to text file should be eliminated.

**Comment by mdiamon** [comment]
[test.txt](https://github.com/JeffersonLab/hps-java/files/1520857/test.txt)

**Comment by afilippi67** [comment]
information in the gbl test file seems to be consistent, truth variables are filled for mc data and distributions look reasonable. The only improvement one could think about is to provide the initial chi2/ndf (for the circle and zfit) which are still zero (they always have been), I suppose it is not read/written correctly in the gbl output file.

**Comment by mdiamon** [comment]
There is only one [chi^2, ndf] available at this point in the code, which is for the overall track.  (There are no longer separate values for the circlefit and the zfit.)  I have now put this as the first entry in the chi^2 and ndf arrays.  Note, the second component of each array will still be 0.

**Comment by JeremyMcCormick** [comment]
Resolved by #280.
