### ISSUE TITLE
Update Edge Corrections for 2016 Data

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#249]
Task is on the pass2 checklist.  First I will update the code for the energy-corrections so that they scale with the B-field.

**Comment by mholtrop** [comment]
Comment from Sebouh on Issue 249:  I completely forgot that I was assigned to do this, but I don't quite remember what this involves.  I have made no progress on this particular issue.  I think Nathan mentioned that I should work on something like this, but I don't remember.

**Comment by mholtrop** [comment]
This should be re-opened as a new task with a more clear description and details on what to do.
