### ISSUE TITLE
Calculate Calorimeter y position with respect to the SVT

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#269]
Calculate the calorimeter y position for top and bottom with respect to the SVT using the technique pioneered by Nathan.
[hps_trackClusterMatching.pdf](https://github.com/JeffersonLab/hps-java/files/1540473/hps_trackClusterMatching.pdf)

**Comment by normangraf** [comment]
org.hps.analysis.alignment.SvtCalorimeterAlignmentDriver plots the track y position at the calorimeter versus nSigma of the track-cluster match.
This plot exhibits an edge when the track comes within half a crystal width from the edge of the calorimeter. Fitting this edge position as a function of nSigma and extrapolating to nSigma=0 gives the crystal center position in the SVT coordinate system.

**Comment by normangraf** [comment]
Using a partial fee skim from the 2015 runs 5796 and 5797 I get the following plots.
![fee_svtecalalignment_top](https://user-images.githubusercontent.com/14838926/33776167-65db915e-dbf5-11e7-86a9-084ef8bc08bd.png)
![fee_svtecalalignment_bottom](https://user-images.githubusercontent.com/14838926/33776171-6684968c-dbf5-11e7-9b0c-2bcc919bd4b5.png)

**Comment by normangraf** [comment]
Taking the first slice and overlaying them shows remarkably good agreement between top and bottom, with the middle of the second row of ECal crystals positioned at y=42.5mm.
![fee_svtecalalignment_slice0_topbottom](https://user-images.githubusercontent.com/14838926/33776263-a7f7fb2c-dbf5-11e7-8a65-51132dddb0fe.png)

**Comment by JeremyMcCormick** [comment]
Resolved by #270.
