### ISSUE TITLE
Maximum raw tracker hits per event

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#271]
adds a cut to the RawTrackerHitFitterDriver, causing it to skip an event if there are more than _maxRawHits_ raw tracker hits in the event.  Also adding a setter for this value.  

Tentatively, I am setting the default value of _maxRawHits_ to 300.  This cuts out about 0.3% of good trident events in both 2015 and 2016 datasets.

**Comment by mholtrop** [comment]
This is a duplicate of #267
