### ISSUE TITLE
Generate 3D representations for detector and data elements

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#275]
It would be useful to have 3D representations of the HPS detector and data elements (tracks, clusters, etc.) for use in event displays for publications.

**Comment by normangraf** [comment]
First pass at the detector. Use Adobe Acrobat or Reader to access the interactive 3D model in the pdf.
[hps.pdf](https://github.com/JeffersonLab/hps-java/files/1563470/hps.pdf)

**Comment by JeremyMcCormick** [comment]
Hi, Norman.

Do I need a plugin to load this correctly?  I noticed that Chrome is unhappy with the pdf and just shows a yellow box.  Maybe I need to use Acrobat instead?

Also, I noticed you are implementing this in a Driver.  I think a better idea would be implementing a detector output format, because with your system event data will need to be loaded just to output the 3D model, which I'm not sure makes much sense.  It may be more complicated to do it this way but I think in the long run it would be a better framework.

**Comment by JeremyMcCormick** [comment]
Another path here could be LCDD -> GDML -> ROOT.  The ROOT geometry engine is actually quite nice for displaying 3D models.

**Comment by normangraf** [comment]
You have to use Adobe Acrobat or Reader. None of the other pdf readers support 3D.

**Comment by normangraf** [comment]
I'm just using a Driver to work out the software. Once I have a coding solution in place I definitely would like to have a standalone solution to draw just the detector. Of course, to access event-level data it would have to be incorporated into a Driver.

**Comment by normangraf** [comment]
I'm looking for a solution that allows us to generate event and data displays for a general audience and for use in publications. I agree that the GDML -> ROOT path is nice for displaying the geometry. I've also seen some nice TEve-based event displays. But these only work if you have root installed. And Windows is no longer supported.

**Comment by normangraf** [comment]
With the jsroot server now installed at JLab, we should be able to serve up a root TGeo object in browsers.

 slic -g HPS-PhysicsRun2019-v1-4pt5.lcdd -G HPS-PhysicsRun2019-v1-4pt5.gdml

This can be visualized from within root via:

>root
root [0] TGeoManager* geom = TGeoManager::Import("HPS-PhysicsRun2019-v1-4pt5.gdml")
root [1] geom->GetTopVolume()->Draw("ogl")
root [2] TFile f("HPS-PhysicsRun2019-v1-4pt5_geo.root", "RECREATE")
root [3] geom->Write()

This file can now be put on our jsroot server at JLab.

**Comment by mholtrop** [comment]
You can see this at: http://nuclear.unh.edu/HPS/Detector 
The script that generated the ROOT geometry file from the LCDD is in his-java/detector-data/gdml/scripts and is called Show_HPS_lcdd.py.
