### ISSUE TITLE
Create a Detector for the pass7 reconstruction of the 2015 1.5mm runs

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#276]

**Comment by JeremyMcCormick** [comment]
Can we use one of the 'nominal' models and enable the db alignment constants for the SVT?  Or is this not sufficient?

**Comment by normangraf** [comment]
I was going to do this as one of my checks.

Can you check what the database opening angle entry is for the 1.5mm runs?


Here is what Alessandra recommended in the slack alignment channel:


The parameters to be adjusted in the compact.xml file to provide a 1.5 mm detector are:                                                                                                                                              <millepede_constant name="13100" value="0.0031"/>   and                                                                                                                                                                  <millepede_constant name="23100" value="-0.0033"/>                                                                                                                                                                         replacing the defaults set to zero



________________________________

**Comment by normangraf** [comment]
I have created a new detector for possible use in the pass7 reconstruction of the data with the SVT @ 1.5mm. As its name implies, HPS-EngRun2015-1_5mm-v6-0-fieldmap, is based on the HPS-EngRun2015-Nominal-v6-0-fieldmap detector with the above two modifications to the millepede parameters 13100 and 23100.

**Comment by normangraf** [comment]
I have skimmed a set of Møller candidates from run 5611 and reconstructed them using both the HPS-EngRun2015-Nominal-v6-0-fieldmap (enabling database SVT alignment) and the HPS-EngRun2015-1_5mm-v6-0-fieldmap detectors. The results are quite similar but there are notable differences. Here are just a few.
Here is the Unconstrained vertex mass:
![5611_unconstrainedmollermass](https://user-images.githubusercontent.com/14838926/34065379-12b15dc6-e1b6-11e7-8e5f-2f1239cb0eab.png)
First off, there are ~1.5% fewer events passing my analysis cuts using the new detector. But the mean is slightly lower and the width marginally narrower.

Here is the Target Constrained mass:
![5611_targetconstrainedmollermass](https://user-images.githubusercontent.com/14838926/34065436-6b40436c-e1b6-11e7-8b0a-1254b92b1947.png)
Again, fewer entries, but lower mass and narrower distribution.
Here's the overlay, although it's not very illustrative:
![5611_targetconstrainedmollermassoverlay](https://user-images.githubusercontent.com/14838926/34065450-949bdc30-e1b6-11e7-8c0f-8048567f3f35.png)
The track chi-squared/dof is shifted to lower values with the new detector.
![5611_unconstrainedmollertrackchisquared](https://user-images.githubusercontent.com/14838926/34065466-af3a0ae4-e1b6-11e7-9634-b16508e69d7b.png)

**Comment by normangraf** [comment]
I do not know why I do not get identical results when running these two detectors. Here are my recon commands:

>java -cp hps-distribution-4.1-SNAPSHOT-bin.jar org.hps.evio.EvioToLcio -r -x /org/hps/steering/recon/EngineeringRun2015FullRecon.lcsim -d HPS-EngRun2015-1_5mm-v6-0-fieldmap -D outputFile=output/2015_5611_mollerskim_HPS-EngRun2015-1_5mm-v6-0-fieldmap 2015_5611_mollerskim.evio -e 10000

and

>java -Dorg.hps.conditions.enableSvtAlignmentConstants -cp hps-distribution-4.1-SNAPSHOT-bin.jar org.hps.evio.EvioToLcio -r -x /org/hps/steering/recon/EngineeringRun2015FullRecon.lcsim -d HPS-EngRun2015-Nominal-v6-0-fieldmap -D outputFile=output/2015_5611_mollerskim_HPS-EngRun2015-Nominal-v6-0-fieldmap_enableSvtAlignment 2015_5611_mollerskim.evio -e 10000

**Comment by normangraf** [comment]
`diff detector-data/detectors/HPS-EngRun2015-1_5mm-v6-0-fieldmap/compact.xml detector-data/detectors/HPS-EngRun2015-Nominal-v6-0-fieldmap/compact.xml
6,7c6,7
<     <info name="HPS-EngRun2015-1_5mm-v6-0-fieldmap">
<         <comment>HPS detector for 2015 Engineering Run, SVT at 1.5mm.
---
>     <info name="HPS-EngRun2015-Nominal-v6-0-fieldmap">
>         <comment>HPS detector for 2015 Engineering Run.
767c767
<            <millepede_constant name="13100" value="0.0031" /> 
---
>            <millepede_constant name="13100" value="0.00" /> 
772c772
<            <millepede_constant name="23100" value="-0.0033" />  
---
>            <millepede_constant name="23100" value="-0.000" />  `

**Comment by normangraf** [comment]
```
diff detector-data/detectors/HPS-EngRun2015-1_5mm-v6-0-fieldmap/compact.xml detector-data/detectors/HPS-EngRun2015-Nominal-v6-0-fieldmap/compact.xml
6,7c6,7
<     <info name="HPS-EngRun2015-1_5mm-v6-0-fieldmap">
<         <comment>HPS detector for 2015 Engineering Run, SVT at 1.5mm.
---
>     <info name="HPS-EngRun2015-Nominal-v6-0-fieldmap">
>         <comment>HPS detector for 2015 Engineering Run.
767c767
<            <millepede_constant name="13100" value="0.0031" /> <!-- + means opening-->
---
>            <millepede_constant name="13100" value="0.00" /> <!-- + means opening-->
772c772
<            <millepede_constant name="23100" value="-0.0033" />  <!-- - means opening -->
---
>            <millepede_constant name="23100" value="-0.000" />  <!-- - means opening -->
```

**Comment by afilippi67** [comment]
I tested the HPS-EngRun2015-1_5mm-v6-0-fieldmap running on some events of run 5412 (reading the compact.xml file) and the alignment looks good to me, as can be seen from trend of the mean values of GBL residuals (for instance): 
![mean__topbot_gbl](https://user-images.githubusercontent.com/6739214/34940566-4bad1ff0-f9f0-11e7-9cca-93f08113207e.gif)

so this detector should be considered as validated as best alignment so far for 2015 1.5 mm runs.
By the way, the opening angles which are modified in the compact.xml stand as millepede offsets but they are NOT determined by millepede. The millepede framework for these angles does not exist in hps-java (it was never written); millepede is to be used only for the determination of sensor displacements/rotations, but not for global parameters (of any kind).
