### ISSUE TITLE
Create driver to remove specified ranges of event numbers in specified runs

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#279]
The new driver created in this issue will use the steering file to determine what ranges of event numbers in which runs will be removed.  

What do I plan to use this for?
We did not record the bias voltages during some of our early runs in 2015.  I found ranges of events where the bias was probably off by looking for event ranges where the raw SVT hit counts were exceedingly high.  There were only small number of such ranges of events.  I plan to put this driver in the steering file in order to remove the ranges of events where I think the bias was probably off.

**Comment by JeremyMcCormick** [comment]
Probably better that this be based on a detector condition so that we don't have to use hacked up steering files going forward.

**Comment by sebouh137** [comment]
Agreed... After talking with Rafo on Friday, I decided that we are going to
put the bias-on intervals into the conditions database for these runs, just
like we did with the data we took while Mya was recording the biases.  That
way we can use the same steering files as before.   Tomorrow's meeting
should clear up how I got these bias-on intervals which I sent to the
#project-2015pass7 slackay channel.  (we should update the name of the
channel to pass8)

**Comment by JeremyMcCormick** [comment]
No longer relevant - this is being done with conditions records instead.

**Comment by sebouh137** [comment]
agreed
