### ISSUE TITLE
Document ntuple fields

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#282]
Need to document what the fields are in the ntuples created by TupleMaker etc.

A Confluence page with a table describing the fields would be useful.

**Comment by mdiamon** [comment]
Preliminary draft of documentation at https://confluence.slac.stanford.edu/display/hpsg/Tuple 
@mrsolt : does not include Truth versions of tuples yet.  Are you still the only one using these?

**Comment by JeremyMcCormick** [comment]
This looks great.  I'm going to reopen this item for now.  :)

**Comment by mdiamon** [comment]
Question for the tuple folks: are the fields TrkHits and NTrackHits exact duplicates?

**Comment by mdiamon** [comment]
Another question for the tuple folks: The TrkEcalX and TrkEcalY fields are found using TrackUtils.getTrackPositionAtEcal, which calls TrackUtils.extrapolateTrack.  This is *different* from what is done in TrackDataDriver, which extrapolates the track to the ECal (and adds a new TrackState-atECal to the track) using TrackUtils.extrapolateTrackUsingFieldMap.  I would prefer for the tuple-maker to use the same extrapolation as TrackDataDriver ... but was there some reason for using a different method here?

**Comment by hszumila** [comment]
Nope! Feel free to change it. Used to be correct.

**Comment by JeremyMcCormick** [comment]
Should we add doc for the MC tuple output as well?  (Not sure if there are additional variables.)
