### ISSUE TITLE
Add MC run numbers for different beam energies

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#283]
For instance, need 4.4 GeV beam energy from True Muonium studies.

Suggested scheme:

1000000 - base L0 MC run number; no beam energy
1000001 - 1.05 GeV
1000002 - 1.92 GeV
1000003 - 2.3 GeV
1000004 - 4.4 GeV

assuming all these are needed

**Comment by brigidcrowe** [comment]
We need 6.6 GeV for the True Muonium studies.
I suggest replacing 1.92 GeV with 6.6 GeV.
