### ISSUE TITLE
Create FEE filter for MC

### ISSUE THREAD

**Issue by brigidcrowe** [JeffersonLab/hps-java#288]
The current FEE filter checks for a singles trigger, and will therefore not work for Monte Carlo. It will work if this option is disabled in a parallel driver, or an option is added to the original one. A new MC steering file can also be made to perform FEE cluster filtering before reconstruction.

**Comment by cbravo135** [comment]
An FEE trigger now exists: https://github.com/JeffersonLab/hps-java/blob/master/ecal-readout-sim/src/main/java/org/hps/readout/trigger2019/FEETrigger2019ReadoutDriver.java
