### ISSUE TITLE
Fetching TrackState momenta

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#315]
The TrackState parameterization is based on curvature, which requires bfield to convert to momentum.  The BaseTrackState has a computeMomentum(double bfield) method, which is automatically called by the setParameters(double[] p, double bfield) method and by some -- but not all -- of the constructors.  This sets the BaseTrackState's internal momentum members, which are fetched by the getMomentum() method.  Unfortunately this means it is possible to do getMomentum() on a BaseTrackState whose computeMomentum was never called (or was called with an inaccurate bfield value, since sometimes the bfield changes within the region of validity of a TrackState)... which gives unreliable results.  To address this:
- every place in the code where a TrackState is created, immediately call its computeMomentum with a bfield value that is correct at least somewhere in the region of validity.
- deprecate the getMomentum() method, so that computeMomentum(bfield) is used instead.  The bfield should always be specified when getting the momentum, since the bfield can vary within the region of validity.

**Comment by mholtrop** [comment]
Miriam: No longer an issue. Closed.
