### ISSUE TITLE
Fix Pz error for vertexing

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#330]

**Comment by bloodyyugo** [comment]
I missed a term in the momentum covariance calculation.  It should be: 

C_ij=delta_ij (E_i)^-1 - (E_i)^-1(D_i)TC_0j 

...I forgot the delta_ij(E_i)^-1 term.  Adding that improves the rho pulls quite a bit.  I'll point this to Matt Solt for further testing.

**Comment by mdiamon** [comment]
Closed by PR #348
