### ISSUE TITLE
EvioToLcio crashes when processing multiple files sequentially

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#334]
When running over multiple evio files (from different runs) in sequence, a crashes occurs at the start of the second file.  It's something weird in the RawTrackerHitFitterDriver: see attached screenshot
<img width="948" alt="eviotolcio crash" src="https://user-images.githubusercontent.com/28606323/47481986-25206800-d7ea-11e8-859b-3d45f79852e0.PNG">

**Comment by JeremyMcCormick** [comment]
If it is from two different runs, there's probably an issue with conditions setup in the Driver or something related.  We should make sure the new conditions are being activated properly for the second run.

**Comment by JeremyMcCormick** [comment]
I want to say this class is not designed to process multiple EVIO files from different runs.  Should this be fixed?  It might be more work than it is worth (just process them in separate jobs).

**Comment by JeremyMcCormick** [comment]
The class is not designed to handle EVIO files from different runs.  They should be converted separately.  I'm closing this.
