### ISSUE TITLE
DatabaseConditionsManager does not hold initialized state correctly.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#336]
The DatabaseConditionsManager does not retain the initialization when it is setup in one part of the code and then retrieved in another. This breaks the functioning of the CommandLineTool.java code.

In the following lines of PrintCommand.java, the code aborts:

```
final void execute(final String[] arguments) {
        final CommandLine commandLine = this.parse(arguments);
        final DatabaseConditionsManager conditionsManager = this.getManager();
        if (!conditionsManager.isInitialized()) {
            throw new RuntimeException("conditions system is not initialized");
        }
```

because the conditionsManager that is retrieved with the this.getManager() is not initialized.

**Comment by mholtrop** [comment]
Seems that we can simply fix this in org.apache.commons.cli.CommandLine.AbstractCommand.java by changing code that creates new DatabaseConditionsManager to:
```   public DatabaseConditionsManager getManager() {
        if (manager == null) {
            manager = DatabaseConditionsManager.getInstance();
        }
        return manager;
    }
```

**Comment by mholtrop** [comment]
Jeremy suggests to make the constructor for DatabaseConditionsManager private, so only getInstance() works. See: https://heavyphotonsearch.slack.com/archives/C449ZNYAV/p1541093083015100 and following conversation.

This should be done in a new "feature request".

**Comment by JeremyMcCormick** [comment]
Resolved
