### ISSUE TITLE
Suppress overwhelming amount of extraneous printout in tracking recon.

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#339]
The current output, of the form:

23

   0  -    4 :      0.000000     0.000000     0.000000     6.939782   -69.855911
   5  -    9 :      0.049422    67.258980    89.062447  -900.527305    -1.831915
  10  -   14 :  -1357.563621   285.816946 -6097.417227   -13.099928 -5420.010410
  15  -   19 :   -270.942579  5769.161056    21.691966  6254.679035    68.121699
  20  -   23 :  -1476.174834    -6.490679 -1463.726223

Is overwhelming.
Please suppress. I'll approve the PR immediately.

**Comment by normangraf** [comment]
Miriam, you should be able to simply fetch your patch of GblTrajectory.java from iss318.

**Comment by mdiamon** [comment]
done by PR #341
