### ISSUE TITLE
Create the 2019 MC detector for trigger studies.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#353]
After iss40 is merged, the hodoscope will be defined. This issue can then be executed to construct the 2019 detector, which will also need L0 and an updated L1.

**Comment by mholtrop** [comment]
New detector is complete, but will need further testing in MC. 
Would be better if this can be merged, so testing can be done on "master".
![physicsrun2019_detector_v0](https://user-images.githubusercontent.com/4603874/50105566-11e2b500-01fb-11e9-8b52-2416b0fdae71.png)

**Comment by mdiamon** [comment]
Done by PR #378
