### ISSUE TITLE
In the integration tests, loosen RMS test on ./TargetConstrainedV0Vertices/V0 Vertex z

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#354]
By its nature, ./TargetConstrainedV0Vertices/V0 Vertex z should have an RMS of nearly zero. Typical values are of order 1E-7, less than a single bin in the histogram, which means that minor variations in the machine running the tests can cause the comparison to fail. 

Proposal is to write a simple exception for _this specific test only_ to have a looser requirement: RMS < 1E-6, instead of  tolerance*(rms of reference histogram).
This should catch all cases where the RMS is larger than a bin, i.e. situations where the target constant is failing.

**Comment by mdiamon** [comment]
Closed by PR #355
