### ISSUE TITLE
Put non-cluster-matched tracks in FinalStateParticles

### ISSUE THREAD

**Issue by bloodyyugo** [JeffersonLab/hps-java#370]
This issue changes the collection the tracks (<FEE pCut) that don't have a matching cluster from "OtherElectrons" to "FinalStateParticles" so that these tracks will get vertexed as well.  

We'll have to decide later whether this is the desired handling of these tracks.

**Comment by normangraf** [comment]
Please code this in such a way that we can decide at runtime via the steering file: e.g. have a setter to toggle a boolean includeTrackOnlyElectronsInFSP.

**Comment by bloodyyugo** [comment]
I think this is done?
