### ISSUE TITLE
Update Conditions DB for 2019 Detector

### ISSUE THREAD

**Issue by mrsolt** [JeffersonLab/hps-java#375]
Update Conditions DB for 2019 Detector. The L1 module will be replaced with an L0 module which means it will have a slot/hole sensor. The conditions DB needs to be updated so the readout can work.

**Comment by JeremyMcCormick** [comment]
I need more info here.  What tables/data need to be added or changed?

**Comment by JeremyMcCormick** [comment]
This is out of date, because we will be using a geometry with L0 and the Tracker2017 subdetector.  I will close this for now.
