### ISSUE TITLE
Update SVT Positions for 2019 Detector

### ISSUE THREAD

**Issue by mrsolt** [JeffersonLab/hps-java#379]

**Comment by normangraf** [comment]
Now that the detector is installed, we need to process the survey numbers and propagate them to the compact description. Notice that the z separation of the top and bottom pairs of slim sensors is different for Layer0 and Layer 1
![Snap1](https://user-images.githubusercontent.com/14838926/58193730-858c6080-7c78-11e9-996a-c5c98a9057ad.png)

**Comment by omar-moreno** [comment]
@normangraf @mrsolt What is the status of this?
