### ISSUE TITLE
Old ECal description in HPS-PhysicsRun2016-Pass2 detector

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#396]

**Comment by normangraf** [comment]
An older version of the Ecal description in the compact.xml was picked up when this detector was being built. This is now fixed for HPS-PhysicsRun2016-Pass2, HPS-PhysicsRun2016-Pass2-v0 and HPS-PhysicsRun2016-Pass2-v0_nofield.

**Comment by mholtrop** [comment]
Is this in master, and can this issue be closed?

**Comment by JeremyMcCormick** [comment]
Should be resolved.
