### ISSUE TITLE
Write out all vertex constrained fits, if unconstrained vertex passes chi2 cut.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#398]
Instead of getting rid of the cut completely, we can run on the unconstrained vertex fit chi2. If that cut is passed, then all vertex constrains are written to LCIO.

This then makes sure that if a vertex is written, we always have all 3 variants of the constraints. It also avoids the issue noticed by Matt Solt that for the tuples the bsc and unc vertexes need to be available.

**Comment by bloodyyugo** [comment]
I think this is done...merged?

**Comment by mholtrop** [comment]
Merged in #403, a real embarrassment saved by Miriam.
