### ISSUE TITLE
Account for trigger jitter in SVT hits

### ISSUE THREAD

**Issue by bloodyyugo** [JeffersonLab/hps-java#404]
This is a proposed change to the SVT hit timing code which subtracts the RF-referenced, highest-energy cluster time from each fitted SVT hit times.  

This removes the SVT-hit-by-hit and SVT-hit-ECal cluster correlations (and downstream to tracks) making the apparent width of these distributions when plotted by themselves (not referenced to anything else) much narrower.  A similar effect can be done currently by calculated the SVT hit time referenced to its matched cluster or the SVT hit times referenced to the mean track time.  

We'll have to decide if we want to include this change in production code or not, but here is the code.

**Comment by bloodyyugo** [comment]
issued pull request (iss404)

**Comment by brigidcrowe** [comment]
So did we decide that this is for sure going into official 2016 MC production?
Is it ready for testing?


________________________________

**Comment by mholtrop** [comment]
Included into #410 issue

**Comment by JeremyMcCormick** [comment]
Resolved by PR #417.
