### ISSUE TITLE
Improve integration testing of readout module

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#407]
Currently, there is not a good test for the sim readout step that checks the output data thoroughly.  We need this before any major changes are merged that effect this module so we can verify what we have and make sure the results do not change if the code is significantly altered.

**Comment by mccaky** [comment]
I think Issue #317 is a duplicate of this - we should probably merge them together.

**Comment by JeremyMcCormick** [comment]
Closing for now as it is inactive.
