### ISSUE TITLE
beamspot constraint gives some very low chi-squared probabilities

### ISSUE THREAD

**Issue by bloodyyugo** [JeffersonLab/hps-java#410]

**Comment by bloodyyugo** [comment]
This popped up when the mouse cuts were first used to reco MC (though we see it in data too)...the chi^2 probabilities for some bs-constrained V0's are very low ~<10^-6 and this appears to happen more has the V0 is more displaced (by studying displaced A' MC).

**Comment by bloodyyugo** [comment]
The change in reference position was not properly accounted for in beamspot-constraint calculations.  Remember, we had to vertex, shift reference point, re-vertex in vertexing chain to account for change in pX (circle) for displaced vertices.  MOSTLY effects the chi^2, though parameters are changed a little (I think for the better).

**Comment by bloodyyugo** [comment]
Also add the Vx,y,z errors to the parameters saved in the Vertex object

**Comment by JeremyMcCormick** [comment]
Resolved by PR #417.
