### ISSUE TITLE
Layer 1 of Hodoscope needs to be shifted

### ISSUE THREAD

**Issue by rafopar** [JeffersonLab/hps-java#415]
L1 of Hodo is shifted by 2 mm towards positron side

**Comment by JeremyMcCormick** [comment]
@rafopar 

Bit vague...

What is the issue here?  The compact detector description needs to be updated?

**Comment by JeremyMcCormick** [comment]
@rafopar 

It seemed from discussion in the software meeting that this was already done.  Can you confirm?

**Comment by rafopar** [comment]
Hi @JeremyMcCormick , I am waiting @mccaky to confirm this, my change by 2 mm was trivial, however Kyle wants to check some other staff, before confirming this
