### ISSUE TITLE
Crash with Matrix is Singular Error

### ISSUE THREAD

**Issue by mrsolt** [JeffersonLab/hps-java#426]
We have seen this issue before, where a track can't find one of the hits during the GBL refit and then crashes. I found the place to patch this. Easy fix.

**Comment by JeremyMcCormick** [comment]
This is a duplicate of #416 so I'm closing (use the previously created issue).

**Comment by JeremyMcCormick** [comment]
oops

**Comment by JeremyMcCormick** [comment]
Resolved by PR #428.
