### ISSUE TITLE
Missing DAQ map for 2019 SVT detector model

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#427]
Recon and readout code crashes because DAQ map doesn't exist for L0. 

This is needed for run 1000000 MC readout and reconstruction.

TODO: put stack trace here

**Comment by omar-moreno** [comment]
The 2019 detector geometry is using an L0 module for layer 1.  This means that there are an extra 4 sensors that aren't accounted for in the DAQ map.   However, this is not the baseline design that we should be using for simulation given that replacement of layer 1 with an L0 module is unlikely.  Instead, we should be using the 2017 detector. For now, I'll mark this as "wont fix".  However, if layer 1 ends up being replaced with a L0 module, I'll go ahead and fix the DAQ map.
