### ISSUE TITLE
Update 2019 detector to use HPSTracker2017 instead of 2019

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#432]
This is needed so the detector works with the run 1e6 detector conditions.  It uses the L0 geometry instead of L1 so the SVT DAQ map works.

**Comment by JeremyMcCormick** [comment]
This didn't seem to be a problem when I checked with the 2019 v0 detector.  

Closing for now.

**Comment by JeremyMcCormick** [comment]
This has become part of #420 due to dependence on updated Hodoscope geometry classes, but I will leave the issue up for now.

**Comment by mholtrop** [comment]
See pull #485 for iss464 which addresses this detectpr/
