### ISSUE TITLE
HPS-2016 steering file for running full recon over already reconstructed lcio file

### ISSUE THREAD

**Issue by bloodyyugo** [JeffersonLab/hps-java#450]
Add a steering file to run hps-java full reconstruction over an already recon-ed lcio file.  This add a single driver <PreCleanupDriver/> which removes all reco collection at start of event.

**Comment by bloodyyugo** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<lcsim xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="http://www.lcsim.org/schemas/lcsim/1.0/lcsim.xsd">
    
    <execute>
        <driver name="PreCleanupDriver"/>   
        
        <driver name="EventFlagFilter"/>
        
        <driver name="RfFitter"/>
 
                
        <driver name="EcalRunningPedestal"/>
        <driver name="EcalRawConverter" />
        <driver name="EcalTimeCorrection"/>
        <driver name="ReconClusterer" />
        <driver name="ClusterRFTimeCorrDriver"/>
        <driver name="CopyCluster" />
        
        <driver name="RawTrackerHitSensorSetup"/>
        <driver name="RawTrackerHitFitterDriver" />
        <driver name="TrackerHitDriver"/>
        <driver name="HelicalTrackHitDriver"/>
        
        <driver name="TrackReconSeed345Conf2Extd16"/>       
        
        <driver name="TrackReconSeed456Conf3Extd21"/>
        
        <driver name="TrackReconSeed123Conf4Extd56"/>
         
        <driver name="TrackReconSeed123Conf5Extd46"/>
        
        <driver name="MergeTrackCollections"/>
        <driver name="GBLRefitterDriver" />
        <driver name="TrackDataDriver" />
        <driver name="ReconParticleDriver" />   
        <driver name="LCIOWriter"/>
        <driver name="CleanupDriver"/>
    </execute>    
    <drivers>                     
        <driver name="PreCleanupDriver" type="org.hps.analysis.dataquality.ReadoutCleanupDriver">
            <collectionNames>EcalCalHits EcalClusters EcalClustersCorr FinalStateParticles UnconstrainedMollerCandidates UnconstrainedMollerVertices UnconstrainedV0Candidates UnconstrainedV0Vertices TargetConstrainedMollerCandidates TargetConstrainedMollerVertices TargetConstrainedV0Candidates TargetConstrainedV0Vertices BeamspotConstrainedMollerCandidates BeamspotConstrainedMollerVertices BeamspotConstrainedV0Candidates BeamspotConstrainedV0Vertices GBLKinkData GBLKinkDataRelations MatchedToGBLTrackRelations HelicalTrackHits HelicalTrackHitRelations MatchedTracks GBLTracks MatchedToGBLTrackRelations  RotatedHelicalTrackHits RotatedHelicalTrackHitRelations SVTFittedRawTrackerHits  SVTShapeFitParameters StripClusterer_SiTrackerHitStrip1D TrackData TrackDataRelations TrackResiduals TrackResidualsRelations</collectionNames>
        </driver>
        
        <driver name="EventFlagFilter" type="org.hps.recon.filtering.EventFlagFilter"> 
            <flagNames>svt_bias_good svt_position_good svt_burstmode_noise_good svt_event_header_good</flagNames> 
        </driver> 
        
        <driver name="RfFitter" type="org.hps.evio.RfFitterDriver"/>       

        
        <driver name="EcalRunningPedestal" type="org.hps.recon.ecal.EcalRunningPedestalDriver">
            <logLevel>CONFIG</logLevel>
        </driver>
        <driver name="EcalRawConverter" type="org.hps.recon.ecal.EcalRawConverter2Driver">
        </driver> 
        <driver name="EcalTimeCorrection" type="org.hps.recon.ecal.EcalTimeCorrectionDriver"/> 
        <driver name="ReconClusterer" type="org.hps.recon.ecal.cluster.ReconClusterDriver">
            <logLevel>WARNING</logLevel>
            <outputClusterCollectionName>EcalClusters</outputClusterCollectionName>
        </driver> 
        <driver name="ClusterRFTimeCorrDriver" type="org.hps.recon.ecal.cluster.ClusterRFTimeCorrDriver"/>          
        <driver name="CopyCluster" type="org.hps.recon.ecal.cluster.CopyClusterCollectionDriver">
            <inputCollectionName>EcalClusters</inputCollectionName>
            <outputCollectionName>EcalClustersCorr</outputCollectionName>
        </driver>
        
        
        <driver name="RawTrackerHitSensorSetup" type="org.lcsim.recon.tracking.digitization.sisim.config.RawTrackerHitSensorSetup">
            <readoutCollections>SVTRawTrackerHits</readoutCollections>
        </driver>
        <driver name="RawTrackerHitFitterDriver" type="org.hps.recon.tracking.RawTrackerHitFitterDriver">
            <fitAlgorithm>Pileup</fitAlgorithm>
            <useTimestamps>false</useTimestamps>
            <correctTimeOffset>true</correctTimeOffset>
            <correctT0Shift>true</correctT0Shift>
            <trigTimeScale>55.0</trigTimeScale>
            <useTruthTime>false</useTruthTime>
            <subtractTOF>true</subtractTOF>
            <subtractTriggerTime>true</subtractTriggerTime>
            <subtractRFTime>true</subtractRFTime> 
            <correctChanT0>true</correctChanT0>
            <debug>false</debug>
        </driver>
        <driver name="TrackerHitDriver" type="org.hps.recon.tracking.DataTrackerHitDriver">
            <neighborDeltaT>8.0</neighborDeltaT>
        </driver>
        <driver name="HelicalTrackHitDriver" type="org.hps.recon.tracking.HelicalTrackHitDriver">
            <debug>false</debug>
            <clusterTimeCut>12.0</clusterTimeCut>
            <maxDt>16.0</maxDt>
            <clusterAmplitudeCut>400.0</clusterAmplitudeCut>
        </driver>
        
        <driver name="TrackReconSeed345Conf2Extd16" type="org.hps.recon.tracking.TrackerReconDriver">
            <trackCollectionName>Tracks_s345_c2_e16</trackCollectionName>
            <strategyResource>HPS_s345_c2_e16.xml</strategyResource>
            <debug>false</debug>
            <rmsTimeCut>8.0</rmsTimeCut>
        </driver>                
        <driver name="TrackReconSeed456Conf3Extd21" type="org.hps.recon.tracking.TrackerReconDriver">
            <trackCollectionName>Tracks_s456_c3_e21</trackCollectionName>
            <strategyResource>HPS_s456_c3_e21.xml</strategyResource>
            <debug>false</debug>
            <rmsTimeCut>8.0</rmsTimeCut>
        </driver>                
        <driver name="TrackReconSeed123Conf4Extd56" type="org.hps.recon.tracking.TrackerReconDriver">
            <trackCollectionName>Tracks_s123_c4_e56</trackCollectionName>
            <strategyResource>HPS_s123_c4_e56.xml</strategyResource>
            <debug>false</debug>
            <rmsTimeCut>8.0</rmsTimeCut>
        </driver>                
        <driver name="TrackReconSeed123Conf5Extd46" type="org.hps.recon.tracking.TrackerReconDriver">
            <trackCollectionName>Tracks_s123_c5_e46</trackCollectionName>
            <strategyResource>HPS_s123_c5_e46.xml</strategyResource>
            <debug>false</debug>
            <rmsTimeCut>8.0</rmsTimeCut>
        </driver>             
        <driver name="MergeTrackCollections" type="org.hps.recon.tracking.MergeTrackCollections" />
        <driver name="TrackDataDriver" type="org.hps.recon.tracking.TrackDataDriver" />
        <driver name="ReconParticleDriver" type="org.hps.recon.particle.HpsReconParticleDriver" > 
            <ecalClusterCollectionName>EcalClustersCorr</ecalClusterCollectionName>
            <trackCollectionNames>GBLTracks</trackCollectionNames>
            <includeUnmatchedTracksInFSP>true</includeUnmatchedTracksInFSP>
            <useInternalVertexXYPositions>true</useInternalVertexXYPositions>
            <beamPositionX> -0.224 </beamPositionX>
            <beamSigmaX> 0.125 </beamSigmaX>
            <beamPositionY> -0.08 </beamPositionY>
            <beamSigmaY> 0.030 </beamSigmaY>
            <beamPositionZ> -4.3 </beamPositionZ>
            <maxElectronP> 2.15 </maxElectronP>
            <maxVertexP> 2.8 </maxVertexP>
            <minVertexChisqProb> 0.0 </minVertexChisqProb>
            <maxVertexClusterDt> 2.5 </maxVertexClusterDt>
            <maxMatchDt>10</maxMatchDt>
            <trackClusterTimeOffset>55</trackClusterTimeOffset>
        </driver>  
        <driver name="GBLRefitterDriver" type="org.hps.recon.tracking.gbl.GBLRefitterDriver" >
            <maxTrackChisq5hits> 60. </maxTrackChisq5hits>
            <maxTrackChisq6hits> 84. </maxTrackChisq6hits>
        </driver>
        <driver name="LCIOWriter" type="org.lcsim.util.loop.LCIODriver">
            <outputFilePath>${outputFile}.slcio</outputFilePath>
        </driver>
        <driver name="CleanupDriver" type="org.lcsim.recon.tracking.digitization.sisim.config.ReadoutCleanupDriver"/>
        <driver name="AidaSaveDriver" type="org.lcsim.job.AidaSaveDriver">
            <outputFileName>${outputFile}.root</outputFileName>
        </driver>             
    </drivers>
</lcsim>

**Comment by bloodyyugo** [comment]
...sorry, github won't let me post a .lcsim file here so I copy/pasted text.

**Comment by JeremyMcCormick** [comment]
> ...sorry, github won't let me post a .lcsim file here so I copy/pasted text.

Just check the file into your branch for this issue...

**Comment by JeremyMcCormick** [comment]
@bloodyyugo @normangraf 

Is this resolved now?  (Think we ran this already.)
