### ISSUE TITLE
Implement Final Hodoscope Trigger

### ISSUE THREAD

**Issue by mccaky** [JeffersonLab/hps-java#472]
The hodoscope readout chain is functionally complete and ready for trigger studies. These needs to be performed and the final production hodoscope trigger implemented.

**Tasks:**
- [ ] Perform pile-up trigger studies. The production trigger driver will require the parameters from these.
- [ ] Implement trigger code. The trigger needs to be implemented programmatically in a manner consistent with the hardware behavior.

**Comment by mccaky** [comment]
The trigger code is partially written already and I have a solid description of the hardware behavior from Ben Braydo. The main part is completing the trigger studies with the new pile-up simulation, but that is pending the approval and merger of iss420.

**Comment by mccaky** [comment]
iss420 is now merged and ready. A few bugs were found and fixed in iss480. Once iss480 is merged, trigger studies should be able to start. There is still a small outstanding issue with slight changes in hit time and energy during preprocessing, but this should not preclude trigger studies since the issue is so small.

**Comment by rafopar** [comment]
This is done.
I think @tongtongcao did the final implementation.
Could @tongtongcao or @mccaky comment on this.
Anyway @JeremyMcCormick I think this should be closed.

**Comment by JeremyMcCormick** [comment]
@tongtongcao indicates this can be closed.
