### ISSUE TITLE
Implement Hodoscope Calibrations

### ISSUE THREAD

**Issue by mccaky** [JeffersonLab/hps-java#473]
Final calibrations need to be determined for the hodoscope and input into the conditions database. These include:

- [ ] Gains
- [ ] Noise
- [ ] Pedestals
- [ ] Time Shifts

**Comment by mccaky** [comment]
I believe that noise and pedestals are already good. Rafo should confirm, though.

**Comment by rafopar** [comment]
Gains are obtained with cosmic run and they put into conditions DV before the 2019 run.
@JeremyMcCormick this can be closed.

**Comment by JeremyMcCormick** [comment]
@rafopar indicated this can be closed
