### ISSUE TITLE
SimCalorimeterHit Alters Input Values

### ISSUE THREAD

**Issue by mccaky** [JeffersonLab/hps-java#479]
When creating a `SimCalorimeterHit` in `org.hps.readout.hodoscope.HodoscopePreprocessingDriver` in the `ecal-readout-sim` project, it changes the values of some of the input parameters. For instance, if a truth hit at time `t = 3.771501 ns` is used as a base, and the `SimCalorimeterHit` produced from it presents a time of `t = 3.739202 ns`.

Some portion of the difference may be due to the fact that `SimCalorimeterHit` takes a `float` for its truth data time and energy (despite returning an `double`). However, this should only result in a loss of precision (i.e. `t = 3.771501302719116 ns` to ` t = 3.7715013 ns`). It should not change significant digits in the first few decimal places. Something is likely happening the `SimCalorimeterHit` constructor beyond just assigning the input values.

In `HodoscopePreprocessingDriver`, the method `makeHit(SimTrackerHit, int, double)` handles the creation of the `SimCalorimeterHit`. It is called from the method `process(EventHeader)`. The steering file `SimpleHodoscopeTriggerNoTracker` may be used to run the driver. The issue is not input file specific.

**Comment by mholtrop** [comment]
Kyle what steering file do you use that triggers this problem?
 I currently don't see any that use this driver.  Do I use any SLIC output file (spaced) that has hodoscope hits or do I need a specific file?

**Comment by mccaky** [comment]
This has been resolved. Apparently it was an issue in the code that checked it, so no changes needed to be made.
