### ISSUE TITLE
Hodoscope Readout Chain Bug Fixes

### ISSUE THREAD

**Issue by mccaky** [JeffersonLab/hps-java#480]
This is for correction of minor bugs related to the recent merger of iss420.

**Comment by mholtrop** [comment]
@mccaky Could you give me some more specifics than “minor bugs related to the recent merger of iss420”. I probably lost track as to what the bugs you are referring to actually are.

**Comment by mccaky** [comment]
@mholtrop This is covered in more detail in the pull request (#481), but it has already been reviewed and merged. You can check there for the bullet list of what was changed, if you are curious, though. For now, I'm closing this issue since it has been merged and is no longer needed.

Basically, though, this issue was intended as a catch-all for any minor fixes that didn't make it into the hodoscope readout chain merger, or weren't caught until afterwards.
