### ISSUE TITLE
Add Simple Unit Test of EVIO to LCIO Conversion

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#483]
Read in EVIO files with 2015, 2016 and 2019 data, convert to LCIO, and check the output.

Initial check could just be that collections are not empty, the expected number of objects are there (this will help for testing in case an EVIO reader is reading the wrong collection and creating too many objects), and the data fields have non-zero values, for ADC counts, for instance.

This test could be added on `iss434` where the Hodoscope converter is being developed.

**Comment by omar-moreno** [comment]
For SVT, two test exist.  SvtEvioReader for 2015/2016 data and Phys2019SvtEvioReader for 2019 data.

**Comment by JeremyMcCormick** [comment]
I think for now the recon tests cover this sufficiently as they run from EVIO data.
