### ISSUE TITLE
Test processing of large (~10GB) EVIO files.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#494]
Make sure we can process EVIO files that are ~10GB in size. The larger file size makes sure that each file will have at least one EPICS event. It also makes better use of the tape drives.

These files will probably need to be split into smaller EVIO files so that the reconstruction does not take forever. We do need to check that the large file can also be handled directly.

- [ ] Test direct processing of large file with Evio2Lcio
- [ ] Test splitting up the EVIO file into multiple smaller files.
- [ ] Data processing scripts need to be updated to split large EVIO file locally on farm node and process the resulting smaller files in parallel.

**Comment by baltzell** [comment]
I'm trying to make a big evio file, but the DAQ config settings to do it isn't working.  Sergey's on it.

**Comment by JeremyMcCormick** [comment]
@baltzell @mholtrop 

When there is some sample data available, then please let me know...

**Comment by baltzell** [comment]
Finally got a big file:

`ifarm1401> ls -lh /work/hallb/hps/data/test/hpsecal_009153.evio.00000`
`-rw-r--r-- 1 baltzell hps 9.8G Jun  7 09:31 hpsecal_009153.evio.00000`

It's cosmic trigger with no zero-supression but ECAL HV off, so it's a lot of useless ECAL FADC data.  But perfectly good for a big-file test.

**Comment by mholtrop** [comment]
I tested analyzing a large file. Instead of Nathan's big file, I concatenated five 2016 EVIO files together into a single 10 GB EVIO file.  This file could be opened and analyzed with hps-java's EVIO2LCIO without a problem.

I wrote two C++ utilities:
* evioconcat  -- Combine several EVIO files into one large EVIO file.
* eviosplit      -- Split an EVIO file (set of EVIO files) into a set of smaller EVIO files.

On my laptop (SSD drive), it takes 20 seconds to concatenate five 2GB EVIO files into one large one.
It then takes only 40 seconds to split that large EVIO file into 82 small EVIO files with 25k events each.

Use:
```/data/HPS/HPS_Analysis/Debug/evioconcat -h
evioconcat <options> file1 file2 ... filen 

Options: 
  --outfile  (-o)  : Specify the output file name. [evioconcat.evio] 
  --debug          : Set debug flag to 2
  --quiet          : Be really quiet about all this.
```

```/data/HPS/HPS_Analysis/Debug/eviosplit -h
eviosplit <options> file1 file2 ... filen 

This program will read the input file(s) and produce an set of output files with 
with a maximum of mexevt events. The outputfiles will be named: outfile_xxx.evio 

Options: (short option) 
  --outfile name (-o)  : Specify the output file name base. [eviosplit] 
  --maxevt  num  (-m)  : Maximum number of events in output file. 
  --maxfile num  (-M)  : Maximum number of files that will be created.
  --debug              : Set debug flag to 2
  --quiet              : Be really quiet about all this, set debug flag to 0.```

**Comment by mholtrop** [comment]
Not an issue
