### ISSUE TITLE
Parse new VTP banks for trigger validation

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/hps-java#496]
Email excerpt from Ben:

I attached clonbank.xml (from 1.4.0 CLON PARMS release). The 0xe122 bank is for the VTP trigger bank descriptions (see the "HPS_..." ones). Before we had trigger banks for HPS come from the SSP, but we no longer have the SSP. We have replaced the GTP with the VTP, and the VTP now also integrates the firmware that used to be in the SSP (so now we have a single firmware images for essentially the whole HPS trigger which is a nice simplification).

So the decoding for HPS trigger banks will need to be updated. Here's what has been added:
1) HPS_CLUSTERS now use 4bits for N (the number of hits in the cluster) instead of 3bits (where the count would saturate at 7)
2) HPS_SINGLE_TRIG now has added trigger tags for indicating if it is a top or bottom half trigger, position dependent energy cut pass, and 4 hodoscope cut pass flags
3) HPS_SINGLE_TRIG and HPS_PAIR_TRIG instance can now be 0,1,2,3 (used to be we only had 0,1)
4) HPS_CALIB_TRIG is new and tells us if the cosmic, LED, or hodoscope only trigger fired
5) HPS_MULT_TRIG is new and tells us if the cluster multiplicity trigger the system and what the cluster multiplicity for top, bottom, and total was

I'm still in the middle of putting this into a document, but most of the details in the bank description should be obvious (not all I understand). I'll send a document were further details when I finish it - probably next week.

[clonbanks.xml.gz](https://github.com/JeffersonLab/hps-java/files/3242177/clonbanks.xml.gz)

**Comment by rafopar** [comment]
This is part is done, and the branch iss496 is merged to master
