### ISSUE TITLE
Propagate covariance matrix correctly when changing reference point for perigee track representation

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-java#54]

**Comment by normangraf** [comment]
To test this, it would be very useful to have a method which takes a SimTrackerHit and produces a TrackState. One can then directly plot residuals and pulls to confirm the correctness of the covariance matrix. @omar-moreno @byale-jlab @mrsolt @bloodyyugo

**Comment by omar-moreno** [comment]
I believe this already exists. Let me look around to see if I can find it.

**Comment by normangraf** [comment]
Thanks. I would have thought so, but didn't see anything obvious in TrackUtils.

**Comment by mdiamon** [comment]
Is this part of #154 ?

**Comment by bloodyyugo** [comment]
Yes.

On Jul 31, 2017, at 2:37 PM, Miriam Diamond <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this part of #154<https://github.com/JeffersonLab/hps-java/issues/154> ?

**Comment by mdiamon** [comment]
OK, then let's close this and collapse it into #154 .
