### ISSUE TITLE
LCSimTestRunEventBuilder should not contain ANY 2019 processing classes.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#543]
We should not have hodoscope or VTP ( or TS) processors in the LCSimTestRunEventBuilder base class.

This is an intermediate step issue. Eventually, we need to rip the entire LCSimTestRunEventBuilder out of the class chain, but that is a separate step for later. 

Right now, new processors for EVIO banks that do not exist in the 2015/16 dataset should be added to the new LCSimPhys2019EventBuilder, and no where else.

**NOTE** -- This issue is to be merged with the Run2019Master - not with master.

**Comment by JeremyMcCormick** [comment]
There's 2015 and 2016 stuff in there too. 😆

**Comment by JeremyMcCormick** [comment]
This has been renamed as "Base" instead of "TestRun" via a recent PR - please open an additional issue if further changes are desired.
