### ISSUE TITLE
Catch "Matrix is singular" RuntimeException in GBLRefitterDriver

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#566]
This one keeps cropping up...

**Comment by mholtrop** [comment]
I ran through about 50 EVIO files and did not see a single one. Are you running from Run2019Master?
If so, I would like to know exactly the file and approximately the event number, so I can run it through my debugger.
- Maurik

**Comment by normangraf** [comment]
Hello Maurik,

I’ve been running what I thought was an up-to-date Run2019Master build with the PhysicsRun2019_testRecon.lcsim steering file. I get this error almost every partition.

Can you try the following event?

http://www.lcsim.org/test/hps-java/10064_crashingEvent.evio

Norman

**Comment by omar-moreno** [comment]
Resolved by #568
