### ISSUE TITLE
Investigate issue of SeedTracker discarding L0/L1 hits with 0.0 correction distance

### ISSUE THREAD

**Issue by bloodyyugo** [JeffersonLab/hps-java#583]
Doing recon on 2019 data, we see many errors like:
`[WARNING] org.hps.recon.tracking.TrackerReconDriver process :: 10030 139180643 Discarding track with bad HelicalTrackHit (correction distance 0.000000, chisq penalty 0.000000) Layer = 1`

...only occurs in Layer = 1 (new module 0) and  Layer = 3 (new module 1) ...i.e. the thin sensors.

**Comment by normangraf** [comment]
Could be due to assumptions about the parallax corrections.

**Comment by bloodyyugo** [comment]
I'm not sure what this was or if this is still an issue.  I'm closing.
