### ISSUE TITLE
Create a Track Ambiguity-Resolver

### ISSUE THREAD

**Issue by mdiamon** [JeffersonLab/hps-java#65]
Create a class in hps-java that chooses between potentially-duplicate tracks made using different strategies.  Some options for the ambiguity-resolving strategy will be settable by user.

**Comment by mdiamon** [comment]
branch issue65b: removing conflicting code from other drivers that did some ambiguity-solving work, such that *all* ambiguity-solving is done in MergeTrackCollections driver using the proper solver

**Comment by JeremyMcCormick** [comment]
resolved

**Comment by mdiamon** [comment]
I've found a few more drivers that include ad-hoc methods to do some basic ambiguity-solving work (e.g. removing duplicate/shared tracks).  Re-opening this issue with branch iss65b: remove these old methods, such that _all_ ambiguity-solving is done only in MergeTrackCollections driver using the proper solver
