### ISSUE TITLE
Adjust parameters in PhysicsRun2016TrigSingles0.lcsim for Moeller MC

### ISSUE THREAD

**Issue by tongtongcao** [JeffersonLab/hps-java#650]
Lookin into readout files, there are differences
======= PhysicsRun2016TrigSingles0.lcsim =======
<readoutOffset>37</readoutOffset>               
<readoutWindow>100</readoutWindow>             
vs
========== PhysicsRun2016TrigPairs1_NoTruth.lcsim =============
<readoutOffset>13</readoutOffset>               
<readoutWindow>50</readoutWindow>

**Comment by JeremyMcCormick** [comment]
@tongtongcao Did you fix this?
