### ISSUE TITLE
Trigger drivers for 2019

### ISSUE THREAD

**Issue by tongtongcao** [JeffersonLab/hps-java#655]

**Comment by tongtongcao** [comment]
Fixing bugs:
1) Ecal and hodo share digitization driver. The digitization driver processes truth hits to transform pulses into FADC hits according to hit energy. But unit of hodo gain in database is self-defined (we can call it as kind of charge), instead of MeV. To let the digitization driver can process hodo hits like Ecal hits, we need to do conversion for hodo gain from self-defined-unit/ADC to MeV/ADC.
ps: Hodo gain is set as uniform with unit of MeV/ADC when Kyle did his study, so no problem at that time. But we updated database for hodo gain according to Rafo's analysis.
2) The threshold crossing sample is regarded as a part of NSB, but actually it is a part of NSA for algorithms of FPGA. This bug causes that pulse integration range  shifts one clock-cycle to the left. Change of integration values caused by this issue is slight.
3) Deadtime for pulse integration is 32ns for hardware. But in the code, we use deadtime as 32 clock-cycles. We set interval of signal events as 500ns (i.e. 125 clock-cycle) for 2016 MC, so no significant effects on hits from signal events for 2016 MC data. 

Developing HodoscopePatternReadoutDriver: the driver produces hodoscope pattern objects for Ecal-hodo matching in the trigger simulation. Persistency of Hodo FADC hits is a programmable time. On the other hand, hodo FADC hits is earlier to enter the trigger system than Ecal by a given time. Therefore, for each trigger clock-cycle, hodo FADC hits in [localTime - (persistentTime - timeEarlierThanEcal), localTime + timeEarlierThanEcal + 4] are taken into account to generate hodoscope patterns for all layers.

Developing SinglesTrigger2019ReadoutDriver: comparing to singles trigger readout driver of 2016, hodoscope is added into trigger system. Every clock-cycle, hodoscope patterns are sent into the trigger system, and match VTP clusters by geometry and time to produce trigger signals. 

Updating PairsTrigger2019ReadoutDriver: in the view of software, the pairs trigger readout driver for 2019 is almost the same as the pairs trigger readout driver of 2019. But parameters are updated based on 2019 DAQ configuration.

Three readout steering files:
1) Singles trigger: PhysicsRun2019TrigSingles.lcsim
2) Pairs trigger: PhysicsRun2019TrigPairs.lcsim
3) Pulse trigger: PhysicsRun2019TrigPulse.lcsim

**Comment by mccaky** [comment]
> Developing HodoscopePatternReadoutDriver: the driver produces hodoscope pattern objects for Ecal-hodo matching in the trigger simulation. Persistency of Hodo FADC hits is a programmable time. On the other hand, hodo FADC hits is earlier to enter the trigger system than Ecal by a given time. Therefore, for each trigger clock-cycle, hodo FADC hits in [localTime - (persistentTime - timeEarlierThanEcal), localTime + timeEarlierThanEcal + 4] are taken into account to generate hodoscope patterns for all layers.

Could you expand on what approach you used to accomplish this? The readout system was updated so that there are some formal methods for handling these time offsets automatically that we should use. One of the problems with the old system was that this all had to be put in manually, and we want to avoid falling back on that (if that is the case).

Also, for hodoscope "patterns," I assume you mean the combination of two adjacent scintillators?

> Deadtime for pulse integration is 32ns for hardware. But in the code, we use deadtime as 32 clock-cycles. Fortunately, this bug does not significantly affect 2016 MC since we set interval of signal events as 500ns (i.e. 125 clock-cycle) and frequency of background events is quite low.

Have you modified it so that multiple integrations can be on-going at the same time on a single channel? That is technically possible (though probably not exceedingly likely).

**Comment by tongtongcao** [comment]
> > Developing HodoscopePatternReadoutDriver: the driver produces hodoscope pattern objects for Ecal-hodo matching in the trigger simulation. Persistency of Hodo FADC hits is a programmable time. On the other hand, hodo FADC hits is earlier to enter the trigger system than Ecal by a given time. Therefore, for each trigger clock-cycle, hodo FADC hits in [localTime - (persistentTime - timeEarlierThanEcal), localTime + timeEarlierThanEcal + 4] are taken into account to generate hodoscope patterns for all layers.
> 
> Could you expand on what approach you used to accomplish this? The readout system was updated so that there are some formal methods for handling these time offsets automatically that we should use. One of the problems with the old system was that this all had to be put in manually, and we want to avoid falling back on that (if that is the case).
> 
> Also, for hodoscope "patterns," I assume you mean the combination of two adjacent scintillators?
> 
> > Deadtime for pulse integration is 32ns for hardware. But in the code, we use deadtime as 32 clock-cycles. Fortunately, this bug does not significantly affect 2016 MC since we set interval of signal events as 500ns (i.e. 125 clock-cycle) and frequency of background events is quite low.
> 
> Have you modified it so that multiple integrations can be on-going at the same time on a single channel? That is technically possible (though probably not exceedingly likely).

Hello Kyle,

Thanks for comments.

Here is code in process method:         Collection<CalorimeterHit> fadcHits = ReadoutDataManager.getData(
                localTime - (persistentTime - timeEarlierThanEcal), localTime + timeEarlierThanEcal + 4.0,
                inputCollectionName, CalorimeterHit.class);
You can see I followed the formal methods to get data for each clock-cycle with consideration of persistence, and time shift between ecal and hodo. 
Besides, here is code in startOfData method: localTimeDisplacement = timeEarlierThanEcal + 4.0; 
time displacement relative to system is set. 
Pattern is named referring to FPGA algorithm. It provides hodo-hit-status of hodo layers every clock-cycle. Logic for how to build pattern is hard to explain. Please refer to codes. I will have a discussion in the software meeting.

Nice comments for multiple integrations can happen at the same time on a single channel. I double checked with Ben. Yes, multi integrals may happen at some of the samples.
