### ISSUE TITLE
Fix missing electron-side bottom ECAL clusters

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/hps-java#716]

**Comment by normangraf** [comment]
Calorimeter hits (and therefore also clusters) are missing in the -x, -y quadrant when running the latest master snapshot of hps-java. The issue can be replicated as follows at JLab:

wget https://srs.slac.stanford.edu/nexus/repository/lcsim-maven2-snapshot/org/hps/hps-distribution/4.5-SNAPSHOT/hps-distribution-4.5-20200508.183531-34-bin.jar hps-distribution-4.5-20200508.183531-34-bin.jar

 

java -cp hps-distribution-4.5-20200508.183531-34-bin.jar org.hps.evio.EvioToLcio -x /org/hps/steering/recon/PhysicsRun2019FullRecon.lcsim -r -d HPS-PhysicsRun2019-v2-4pt5 -DoutputFile=tstMaster -e 100 -n 5000 /cache/hallb/hps/physrun2019/data/hps_010677/hps_010677.evio.00000
