### ISSUE TITLE
Verify ecal position correction for 2019 run

### ISSUE THREAD

**Issue by andrea-celentano** [JeffersonLab/hps-java#749]

**Comment by andrea-celentano** [comment]
Branch iss749 with the code to extract the position correction has been merged to master.
Now working on iss732-refactor to VERIFY the correction

**Comment by JeremyMcCormick** [comment]
@andrea-celentano Should this be closed since the relevant branch has been merged?

**Comment by andrea-celentano** [comment]
Hi, yes it can be deleted.

**Comment by JeremyMcCormick** [comment]
@andrea-celentano indicates it is resolved
