### ISSUE TITLE
Re-organizing Track-to-Cluster matching implementation

### ISSUE THREAD

**Issue by alspellm** [JeffersonLab/hps-java#790]
Re-organized Track-to-Cluster Matcher implementation in a similar way to how Clustering algorithms are handled. 
All Track-To-Cluster matching algorithms now extend a TrackClusterMatcher Interface class.
You select which matching algorithm to use via a TrackClusterMatcherFactory. 

This allows us to use different track-to-cluster matching algorithms inside of ReconParticleDriver by passing the algorithm class name through the steering-file.

**Comment by JeremyMcCormick** [comment]
Resolved by #791
