### ISSUE TITLE
Move test files to dedicated directory at JLAB

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#794]
Instead of the group html dir there is a dedicated directory for test data already:

```/group/hps/test-data```

which maps to

https://hpsweb.jlab.org/test-data/

Files should be copied there and the location in the tests updated.

**Comment by omar-moreno** [comment]
Why not make use of git LSF? Are the files too big?

**Comment by JeremyMcCormick** [comment]
The files are already at JLAB. They're just not in the directory that they
should be using...

**Comment by JeremyMcCormick** [comment]
I wouldn't want to require all developers to install the LFS tools for file
access just to run the tests or make them use those commands just to add
test data.
