### ISSUE TITLE
Update all test to use 2016/2019 detectors. 

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-java#829]
Sometimes you just got to move on ... :)

**Comment by JeremyMcCormick** [comment]
This actually breaks down into two issues:

- Removing the 2015 tests, which are similar to the 2016 ones, should there be agreement on doing this
- Adding one or more 2019 tests that actually make some test assertions; the existing one does not do anything but run the recon to make sure it completes without crashing

There are already existing tests that use 2016 data and detectors.
