### ISSUE TITLE
Improve automated testing of reconstruction output

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#83]
For starters, the EngRun2015ReconTest in integration-tests should actually test something!  Right now it just runs the reconstruction on EVIO data without looking at the output.

A Driver should also be added that creates basic AIDA histograms from the recon data.

Norman will provide a skim of ~1000 EVIO events to be used as input.

**Comment by JeremyMcCormick** [comment]
Here is one idea:

- generate reference DQM plots from ~1000 recon events using 2015 and 2016 skimmed EVIO files

- put the ref plots into the test data

- within a TestCase run the recon and generate DQM output

- compare all the DQM histograms to the reference plots

- raise an error if the output is different

The DQM reference plots would need to be updated if there are improvements made which change the output.

**Comment by JeremyMcCormick** [comment]
To be compared against reference data:

- tracking efficiency (# of tracks found)

- track quality (chi squared)

- momentum scale

- momentum resolution

- ecal # clusters

- ecal # crystals per cluster

- ecal energy scale

- ecal energy resolution

- vertex position

- vertex invariant mass

- vertex momentum

- Moller invariant mass resolution

- XY beam spot resolution

- Z beam spot resolution

Need ~1000 FEE events.

**Comment by normangraf** [comment]
Created a branch (iss83) and have committed code to reconstruct and analyze output for 2015 FEE sample. Still need to add a comparator for the output aida file.

**Comment by normangraf** [comment]
Need to improve the selection cuts applied to the input test file.

**Comment by normangraf** [comment]
Now using 10k full energy electron candidates selected from run 5772. Required one and only one cluster, one and only one track, and six hits on the track. Equal numbers of top and bottom.

**Comment by normangraf** [comment]
Reduced the number of events to reconstruct to roughly 1000 to speed up the tests. Comparing number of entries, mean and rms of histograms, added a tolerance to the assertion.

**Comment by JeremyMcCormick** [comment]
Tests of full recon have been added to hps-java by @normangraf.
