### ISSUE TITLE
V0 reconstruction should not be limited to tracks matched to clusters

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-java#831]

**Comment by normangraf** [comment]
We currently create V0s with tracks that are not associated with clusters, so I'm not sure what this issue is about.

**Comment by cbravo135** [comment]
These two lines mean we expect a particle with a track to have the cluster == null for unmatched tracks.
https://github.com/JeffersonLab/hps-java/blob/master/recon/src/main/java/org/hps/recon/utils/TrackClusterMatcherNSigma.java#L652
https://github.com/JeffersonLab/hps-java/blob/master/recon/src/main/java/org/hps/recon/utils/TrackClusterMatcherMinDistance.java#L458

This line means we don't expect to make V0s for particles with a cluster == null.
https://github.com/JeffersonLab/hps-java/blob/master/recon/src/main/java/org/hps/recon/particle/HpsReconParticleDriver.java#L586

Therefore electron-positrons pairs with an unmatched track are not expected to be selected as a V0 candidate.

**Comment by cbravo135** [comment]
btw, this is a duplication of https://github.com/JeffersonLab/hps-java/issues/82

**Comment by omar-moreno** [comment]
Closing and replacing with smaller issues.
