### ISSUE TITLE
Ensure that the KalmanFullTracks collection be added to every event

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#846]
Some events appear not to contain the KalmanFullTracks collection. There is an implicit contract in the reconstruction that Drivers always return their collection to the Event, even if the collection is empty.

**Comment by pbutti** [comment]
Hi Norman,

Can you provide a recipe (input file, steering, evt number..) to reproduce the issue? I can try to take a look. I don't think it's coming from the KalmanPatRecDriver as that driver always create an empty list of tracks and put it in the event

**Comment by normangraf** [comment]
Here is an event which contains the KalmanFullTracks collection
![Snap52](https://user-images.githubusercontent.com/14838926/115068628-5a800b00-9ea7-11eb-8683-2953d7b8e798.png)

**Comment by normangraf** [comment]
This event does not contain that collection
![Snap58](https://user-images.githubusercontent.com/14838926/115068758-826f6e80-9ea7-11eb-9424-bbdac62bebc1.png)

**Comment by normangraf** [comment]
Events were reconstructed from run 10103 using an hps-java 5.1 snapshot and the PhysicsRun2019_pass0_recon.lcsim steering file.

A file containing ~30k clean events with a full-energy cluster in the fiducial region of the ECal yet missing a KF track can be found at:

/nfs/slac/g/hps_data2/data/physrun2019/skim/fee/hps_feeKFPhotonSkim_20210415_HPS_TY_iter4.slcio

Some of these events, such as 10103 120457, do not contain the KalmanFullTracks collection.
Please let me know if you'd like me to skim off only the events exhibiting this behavior.

**Comment by cbravo135** [comment]
Which particular file are you using from run 10103?

**Comment by cbravo135** [comment]
I only have 41 and 42 which have events 6727749 through 7055016. I wrote a python script to explicitly check for the existence of KalmanFullTracks in every single event (via dumpevent) and I see it in every single event from these two files. The really strange thing to me is when I check /nfs/slac/g/hps_data2/data/physrun2019/skim/fee/hps_feeKFPhotonSkim_20210415_HPS_TY_iter4.slcio from @normangraf , I do see the KalmanFullTracks collection in event 120457:
```
bravo@cbravo-hps:~/move$ dumpevent hps_feeKFPhotonSkim_20210415_HPS_TY_iter4.slcio 49 | head

============================================================================
        Event  : 120457 - run:  10103 - timestamp 25588843088 - weight 1
============================================================================
 date:      01.01.1970  00:00:25.588843088
 detector : HPS_TY_iter4
 event parameters: 
 parameter svt_bias_good [int]: 1, 
 parameter svt_burstmode_noise_good [int]: 0, 
 parameter svt_latency_good [int]: 0, 
bravo@cbravo-hps:~/move$ dumpevent hps_feeKFPhotonSkim_20210415_HPS_TY_iter4.slcio 49 | grep KalmanFullTracks
 collection name : KalmanFullTracks
 ```
 Please close this issue.

**Comment by cbravo135** [comment]
Here is the empty collection explicitly seen in the exact event in the exact file @normangraf references and claimed did not exist:
```
 collection name : KalmanFullTracks
 parameters: 

--------------- print out of Track collection --------------- 

  flag:  0x80000000
     LCIO::TRBIT_HITS : 1

 [   id   ] |   type   |    d0    |  phi     | omega    |    z0     | tan lambda|   reference point(x,y,z)        |    dEdx  |  dEdxErr |   chi2   |  ndf   
------------|----------|----------|----------|----------|-----------|-----------|---------------------------------|----------|----------|-------- 
```

**Comment by pbutti** [comment]
Hi @cbravo135 , 

thank you for checking this, I suppose you used the current master branch? Looking at @normangraf event display looks pretty clear that such collection is missing, tho. Could it be a problem of the visualiser that doesn't show an empty collection? I can confirm that dumping that event The KalmanFullTrack collection is created:

pbutti@cent7a:/nfs/slac/g/hps2/pbutti/hipster$ dumpevent /nfs/slac/g/hps_data2/data/physrun2019/skim/fee/hps_feeKFPhotonSkim_20210415_HPS_TY_iter4.slcio 10103 120457
 LCIORandomAccessMgr::getEventMap() recreating event map for direct access (old file) ...

============================================================================
        Event  : 120457 - run:  10103 - timestamp 25588843088 - weight 1
============================================================================
 date:      01.01.1970  00:00:25.588843088
 detector : HPS_TY_iter4
 event parameters: 
 parameter svt_bias_good [int]: 1, 
 parameter svt_burstmode_noise_good [int]: 0, 
 parameter svt_latency_good [int]: 0, 
 parameter svt_position_good [int]: 0, 
 parameter svt_readout_overlap_good [int]: 1, 


[.........]


 collection name : KalmanFullTracks
 parameters: 

--------------- print out of Track collection --------------- 

  flag:  0x80000000
     LCIO::TRBIT_HITS : 1

 [   id   ] |   type   |    d0    |  phi     | omega    |    z0     | tan lambda|   reference point(x,y,z)        |    dEdx  |  dEdxErr |   chi2   |  ndf   
------------|----------|----------|----------|----------|-----------|-----------|---------------------------------|----------|----------|-------- 

 collection name : MatchedToGBLTrackRelations
 parameters: 

--------------- print out of LCRelation collection --------------- 

  flag:  0x0
 fromType : 
 toType : 

| [from_id ] | [ to_id  ] | Weight  |
|------------|------------|---------|
| [03217826] | [03217289] | 1.000e+00|

 collection name : MatchedTracks
 parameters: 

--------------- print out of Track collection --------------- 

  flag:  0x80000000
     LCIO::TRBIT_HITS : 1

 [   id   ] |   type   |    d0    |  phi     | omega    |    z0     | tan lambda|   reference point(x,y,z)        |    dEdx  |  dEdxErr |   chi2   |  ndf   
------------|----------|----------|----------|----------|-----------|-----------|---------------------------------|----------|----------|-------- 
 [03217826] | 00000008 |+3.63e-01 |+4.38e-02 |+6.35e-05 |+2.885e-01 |+4.349e-02 |(+0.00e+00, +0.00e+00, +0.00e+00)|+5.67e-05 |+0.00e+00 |+5.49e+00 |    5
 errors:   +3.247581e-02 | -2.026575e-04, +1.571781e-06 | -4.676772e-07, +4.006497e-09, +1.146933e-11 | +0.000000e+00, +0.000000e+00, +0.000000e+00, +2.337699e-04 | +0.000000e+00, +0.000000e+00, +0.000000e+00, -1.671459e-06, +1.808367e-08 | 
 tracks(id): 
 hits ->[+3217052] [+3217056] [+3217057] [+3217060] [+3217061] 
 radius of innermost hit +4.222027e+01 / mm ,  subdetector Hit numbers : +0
------------|----------|----------|----------|----------|-----------|-----------|---------------------------------|----------|----------|--------

**Comment by cbravo135** [comment]
I am looking at /nfs/slac/g/hps_data2/data/physrun2019/skim/fee/hps_feeKFPhotonSkim_20210415_HPS_TY_iter4.slcio the file @normangraf produced, he should provide a full recipe for the file. I did pretty much the exact same thing @pbutti just did. The first step I was using a dev branch I have which has some of the current PRs all merged, when I saw no issue, I moved to checking the file provided by @normangraf.

**Comment by JeremyMcCormick** [comment]
> Could it be a problem of the visualiser that doesn't show an empty collection?

I think this could be the case....
