### ISSUE TITLE
Enable partial re-reconstruction from lcio files

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#87]
Pass 7 reconstruction for the 2015 data is envisioned to proceed from the existing found and fit tracks and Ecal clusters. Refitting of the tracks will be done with the new geometry, tracks and clusters will be re-associated to form ReconstructedParticles and vertex finding and fitting will be rerun over the new collections. The current reconstruction code is not able to run over output lcio file since persisting our events is lossy.

**Comment by normangraf** [comment]
Code compiles and reconstruction runs, but needs checking.
There is an integration test which processes events in an evio file from scratch, writes out the lcio file, then reads that file back in and processes it.

`cd integration-tests`
`mvn -Dit.test=Pass7ReconTest verify`

Still need to write the code which compares the two output lcio files.

**Comment by normangraf** [comment]
Skipping the raw tracker hit fitting and the track finding results in a speedup of about a factor of 10.

**Comment by normangraf** [comment]
Previous timing results were based on a sample of 100 events. When run over a thousand Møller candidates the speedup is closer to a factor of 40. Presumably this is due to the common time of contacting the database and reading in the geometry, etc.

**Comment by JeremyMcCormick** [comment]
Resolved by PR #112.
