### ISSUE TITLE
Iterate vertex fit

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#89]
The current Billoir vertex fitter uses "perigee" parameters which presuppose that the tracks are in the vicinity of the vertex. TrackStates used for the fit reference the interaction point, so for displaced vertices one should iterate the fit by propagating the tracks to the initially found vertex, calculate the perigee parameters with respect to that initial vertex position, refit and iterate if necessary.

**Comment by normangraf** [comment]
Have a patch which extrapolates tracks to the vertex, recalculates track momenta and vertex mass and updates metadata in the Vertex. Plot shows vertex mass residual as a function of the vertex MC z position before and after the patch. This is for a sample of 50MeV A' events with 100mm decay length.
![aprimemassresvsmcz_fittedvsfixed](https://cloud.githubusercontent.com/assets/14838926/26807318/af37732c-4a0a-11e7-89d9-4b0b3914afc5.png)

**Comment by mholtrop** [comment]
Is this fixed with pull 124 (https://github.com/JeffersonLab/hps-java/pull/124) for issue 89?
If so, this issue should be closed.
