### ISSUE TITLE
SVT conditions use wrong disambiguation strategy when multiple conditions sets are found

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#90]
The `SvtCalibration` class is using the last updated conditions set when multiple conditions sets are found.

This LoC should be removed from this class:

```
@Converter(multipleCollectionsAction = MultipleCollectionsAction.LAST_UPDATED)
```

Then it will use the most recently created conditions set rather than the last updated.

For old versions of hps-java, this bug can be worked around by setting the `updated` field manually to a recent date on conditions sets which should be used for recon.

There are several other SVT conditions classes which used the "last updated" strategy which should probably be changed to "last created."

**Comment by JeremyMcCormick** [comment]
Related to this bug: 

For when older hps-java versions are being run e.g. to reproduce pass results, you may want to manually change in the db the `updated` date of the conditions you want it to use to a recent date.

**Comment by JeremyMcCormick** [comment]
Also, when you get things in the proper state for the current master where all the correct conditions are being loaded for the 2016 runs, then let me know.  I'd like to then make a conditions tag at that point.

**Comment by omar-moreno** [comment]
That's just asking for trouble.  We should be free to update the DB without
having to worry about picking up the wrong conditions.  If this requires
changes to the conditions code, so be it.

On Thu, May 25, 2017 at 12:33 PM, Jeremy McCormick <notifications@github.com

**Comment by JeremyMcCormick** [comment]
There needs to be some way for the system to figure out which conditions set to use when multiple ones are found of the same type for a given run number.  There's no way for it to tell what is the "right one."  How do you think it should be done?

**Comment by JeremyMcCormick** [comment]
> We should be free to update the DB without having to worry about picking up the wrong conditions.

Actually, no, I don't think anyone should just add additional conditions records that overlap existing ones without knowing what they are trying to accomplish.

**Comment by omar-moreno** [comment]
On Thu, May 25, 2017 at 12:41 PM, Jeremy McCormick <notifications@github.com
> wrote:

> We should be free to update the DB without having to worry about picking
> up the wrong conditions.
>
> Actually, no, I don't think anyone should just add additional conditions
> records that overlap existing ones without knowing what you they are trying
> to accomplish.
>

​Obviously, if you are modifying existing conditions I hope you know what
you are trying to accomplish.  But if a change is made, we shouldn't need
to update a timestamp because our conditions code depends on it ... that's
terrible.

**Comment by JeremyMcCormick** [comment]
It seems like setting the system to use "last created" as I've done on this issue branch resolves this at least for pass1 2016.  Should we call this fixed for now?  I can make a conditions tag based on the current config, so that users can easily load the working config.

**Comment by omar-moreno** [comment]
Setting the correct run ranges fixed this. There was no need to
disambiguate since a run is only associates with a single calibration set.
That said, this can be marked as fixed.
