### ISSUE TITLE
set vertex position to -5.0 in MakeTuples2016.lcsim

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/hps-java#92]

**Comment by normangraf** [comment]
I'd like to see an analysis note documenting how this number was derived. @bloodyyugo @baltzell

**Comment by JeremyMcCormick** [comment]
We don't know that the target is at -5 mm for 2016 data.  

@normangraf is working on this and changes will be submitted under a different issue branch.

Closing for now.
