### ISSUE TITLE
Provide steering file for running recon directly on MC output

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#94]
Right now, our working job chain is:

slic -> bunch filter -> readout sim -> recon

It would be nice to be able to reconstruct the MC output directly.

For the ECal, the sim edeps need to be transformed into pulses using (possibly?) FADCEcalReadoutDriver or SimpleEcalReadoutDriver.

I'm not sure what the equivalent Driver classes are for the SVT.

**Comment by JeremyMcCormick** [comment]
Possibly this steering file already does this:

`/org/hps/steering/recon/HPS2014OfflineTruthRecon.lcsim`

Readout with single event triggering:

`/org/hps/steering/readout/HPS2014ReadoutNoPileup.lcsim`

**Comment by normangraf** [comment]
Does the following steering file not work?
EngineeringRun2015FullReconMC.lcsim

**Comment by brigidcrowe** [comment]
Not without the readout collections.

I think Jeremy is wanting to be able to skip that step.



________________________________

**Comment by JeremyMcCormick** [comment]
> Does the following steering file not work?
> EngineeringRun2015FullReconMC.lcsim

That's the one that requires the readout to be run first, as there are some required collections missing if you do not.

**Comment by JeremyMcCormick** [comment]
Won't be fixed.  :-(
