### ISSUE TITLE
Add support title angles to compact associated with HPS-PhysicsRun2016-v5-3-fieldmap_globalAlign

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-java#95]
They are currently missing and I'm not sure what the defaults are.  Just to be sure, they should be put into the compact.xml.

**Comment by afilippi67** [comment]
yes indeed, they are missing, the full part to be include in the file reads as 

             
            <millepede_constant name="13100" value="0.0" /> 
            <millepede_constant name="13200" value="0.0" />
            <millepede_constant name="13300" value="0.0" />
            
            
            <millepede_constant name="23100" value="-0.0" />  
            <millepede_constant name="23200" value="0.0" />
            <millepede_constant name="23300" value="0.0" />



note that for 1.5 mm geometry you need to modify the 13100 and 23100 costants in the following way:
<millepede_constant name="13100" value="0.0031" /> 
<millepede_constant name="23100" value="-0.0033" />

**Comment by omar-moreno** [comment]
This issue was resolved by commit eff68adfc44b345bf17a7baac040a806f593b352.
