### ISSUE TITLE
Use github actions to manage releases, snapshots, and website deployment

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#959]
Note to self: It would be best to configure Github to use https with access tokens for the workflows with the https URL configured in the POM, rather than SSH. I believe this can be done by just using the token of the user that launches the workflow in the .yml file. (Test this on the fork.) 

Using tokens would also be better for workflow authentication as SSH keys shouldn't need to be stored in repository secrets.

**Comment by sarahgaiser** [comment]
Hi @JeremyMcCormick! Could you comment on what website exactly you are talking about? This one: http://www.lcsim.org/sites/hps/ or another website?

**Comment by JeremyMcCormick** [comment]
Yes, that's the one. I want to deploy it to gh-pages instead.

**Comment by sarahgaiser** [comment]
alright, this might be on me not using the website correctly, but I don't know how to access any useful documentation/information through the project website. Could we update the content of the webpage to include a how-to-use and where-to-find information part or move to Doxygen or sth else that's easier to navigate?

**Comment by JeremyMcCormick** [comment]
There's all kinds of pages we can add to the Maven generated site. I'll
look into this once I get gh-pages working with it.
