### ISSUE TITLE
Add source code formatting to build

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#968]
This uses the Eclipse formatting library:

https://code.revelc.net/formatter-maven-plugin

One option could be adding a gh action that triggers with a merge into master or could be executed manually.

**Comment by normangraf** [comment]
Is this different from what we are currently using?

**Comment by JeremyMcCormick** [comment]
> Is this different from what we are currently using?

Sorry if this wasn't clear. I mean a plugin that actually formats the Java code in place rather than just checking for style.

**Comment by normangraf** [comment]
OK. I ask, because I always format my code in Netbeans using Alt+Shift+F and I'd like to be able to continue to do so.
