### ISSUE TITLE
Consistency fix between NDF and TrackerHits in KF tracks

### ISSUE THREAD

**Issue by pbutti** [JeffersonLab/hps-java#969]
@robertprestonjohnson Noticed that there is an inconsistency between the tracker hits and the number of DoF stored in the KF tracks. 
The reason I think is line 
https://github.com/JeffersonLab/hps-java/blob/7e9a7eac08b6229d4f8b8bf02e29cbcc432215b4/tracking/src/main/java/org/hps/recon/tracking/kalman/KalmanInterface.java#L598

where we should pass the number of tracker hits (that get checked by ID > 0) instead of the size of the measurement sites vector.

**Comment by pbutti** [comment]
@normangraf

**Comment by normangraf** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/14838926/230148086-f6046f53-e5ae-45a4-8764-f69412287e57.png)

**Comment by robertprestonjohnson** [comment]
Looks good to me.
